// =============================================================
// pybind11 bindings for SoupBin
// Auto-generated by dsl/gen_pybind.py — DO NOT EDIT BY HAND.
// =============================================================
#include "SoupBin.hpp"
#include "pybind_common.hpp"

namespace py = pybind11;
using namespace EB::py_helpers;
using namespace SoupBin;

PYBIND11_MODULE(SoupBin_pb, m) {
    m.doc() = "exchbuf bindings for SoupBin";

    // ----- enum PktType -----
    {
        auto c = register_enum_struct<PktType>(m, "PktType");
        c.def_property_readonly_static("Debug",
            [](py::object){ return py::cast(PktType{PktType::Debug}); });
        c.def_property_readonly_static("LoginRequest",
            [](py::object){ return py::cast(PktType{PktType::LoginRequest}); });
        c.def_property_readonly_static("LoginAccepted",
            [](py::object){ return py::cast(PktType{PktType::LoginAccepted}); });
        c.def_property_readonly_static("LoginRejected",
            [](py::object){ return py::cast(PktType{PktType::LoginRejected}); });
        c.def_property_readonly_static("LogoutRequest",
            [](py::object){ return py::cast(PktType{PktType::LogoutRequest}); });
        c.def_property_readonly_static("ServerHeartbeat",
            [](py::object){ return py::cast(PktType{PktType::ServerHeartbeat}); });
        c.def_property_readonly_static("ClientHeartbeat",
            [](py::object){ return py::cast(PktType{PktType::ClientHeartbeat}); });
        c.def_property_readonly_static("EndOfSession",
            [](py::object){ return py::cast(PktType{PktType::EndOfSession}); });
        c.def_property_readonly_static("SeqData",
            [](py::object){ return py::cast(PktType{PktType::SeqData}); });
        c.def_property_readonly_static("UnSeqData",
            [](py::object){ return py::cast(PktType{PktType::UnSeqData}); });
    }

    // ----- message Header -----
    {
        using H = Holder<Header>;
        auto c = py::class_<H>(m, "Header")
            .def_static("allocate", &H::allocate, py::arg("cap") = DEFAULT_CAP)
            .def_static("from_bytes", &H::from_bytes)
            .def("__bytes__", &H::to_bytes)
            .def("to_bytes", &H::to_bytes)
            .def("size", &H::size)
            .def("capacity", &H::capacity)
            .def_static("fixed_size", []() { return Header::fixed_size(); })
            .def_static("wire_size",
                [](py::bytes b) {
                    std::string s(b);
                    return Header::wire_size(s.data());
                })
            ;
        c.def_property("pkgLength",
            [](H& h) { return h.msg().pkgLength.to_int(); },
            [](H& h, decltype(h.msg().pkgLength.to_int()) v) { h.msg().pkgLength = v; });
        c.def_property("pkgType",
            [](H& h) { return h.msg().pkgType; },
            [](H& h, PktType v) { h.msg().pkgType = v; });
    }

    // ----- message Debug -----
    {
        using H = Holder<Debug>;
        auto c = py::class_<H>(m, "Debug")
            .def_static("allocate", &H::allocate, py::arg("cap") = DEFAULT_CAP)
            .def_static("from_bytes", &H::from_bytes)
            .def("__bytes__", &H::to_bytes)
            .def("to_bytes", &H::to_bytes)
            .def("size", &H::size)
            .def("capacity", &H::capacity)
            .def_static("fixed_size", []() { return Debug::fixed_size(); })
            .def_static("wire_size",
                [](py::bytes b) {
                    std::string s(b);
                    return Debug::wire_size(s.data());
                })
            ;
        c.def_property("pkgLength",
            [](H& h) { return h.msg().pkgLength.to_int(); },
            [](H& h, decltype(h.msg().pkgLength.to_int()) v) { h.msg().pkgLength = v; });
        c.def_property("pkgType",
            [](H& h) { return h.msg().pkgType; },
            [](H& h, PktType v) { h.msg().pkgType = v; });
        c.def_property("text",
            [](H& h) {
                auto v = h.msg().text();
                return py::bytes(v.data(), v.size());
            },
            [](H& h, py::bytes b) {
                std::string_view sv(b);
                if (h.msg().fixed_size() + sv.size() > h.capacity())
                    throw py::value_error("text exceeds Holder capacity");
                std::memcpy(h.msg().begin() + h.msg().fixed_size(), sv.data(), sv.size());
                h.msg().pkgLength = static_cast<decltype(h.msg().pkgLength.raw_value())>(sv.size());
            });
    }

    // ----- message LoginAccepted -----
    {
        using H = Holder<LoginAccepted>;
        auto c = py::class_<H>(m, "LoginAccepted")
            .def_static("allocate", &H::allocate, py::arg("cap") = DEFAULT_CAP)
            .def_static("from_bytes", &H::from_bytes)
            .def("__bytes__", &H::to_bytes)
            .def("to_bytes", &H::to_bytes)
            .def("size", &H::size)
            .def("capacity", &H::capacity)
            .def_static("fixed_size", []() { return LoginAccepted::fixed_size(); })
            .def_static("wire_size",
                [](py::bytes b) {
                    std::string s(b);
                    return LoginAccepted::wire_size(s.data());
                })
            ;
        c.def_property("pkgLength",
            [](H& h) { return h.msg().pkgLength.to_int(); },
            [](H& h, decltype(h.msg().pkgLength.to_int()) v) { h.msg().pkgLength = v; });
        c.def_property("pkgType",
            [](H& h) { return h.msg().pkgType; },
            [](H& h, PktType v) { h.msg().pkgType = v; });
        c.def_property("session",
            [](H& h) { return fls_to_string(h.msg().session); },
            [](H& h, const std::string& v) { fls_from_string(h.msg().session, v); });
        c.def_property("seqNum",
            [](H& h) { return fls_to_string(h.msg().seqNum); },
            [](H& h, const std::string& v) { fls_from_string(h.msg().seqNum, v); });
    }

    // ----- enum LoginRejectCode -----
    {
        auto c = register_enum_struct<LoginRejectCode>(m, "LoginRejectCode");
        c.def_property_readonly_static("NotAuthorized",
            [](py::object){ return py::cast(LoginRejectCode{LoginRejectCode::NotAuthorized}); });
        c.def_property_readonly_static("NotAvailable",
            [](py::object){ return py::cast(LoginRejectCode{LoginRejectCode::NotAvailable}); });
    }

    // ----- message LoginRejected -----
    {
        using H = Holder<LoginRejected>;
        auto c = py::class_<H>(m, "LoginRejected")
            .def_static("allocate", &H::allocate, py::arg("cap") = DEFAULT_CAP)
            .def_static("from_bytes", &H::from_bytes)
            .def("__bytes__", &H::to_bytes)
            .def("to_bytes", &H::to_bytes)
            .def("size", &H::size)
            .def("capacity", &H::capacity)
            .def_static("fixed_size", []() { return LoginRejected::fixed_size(); })
            .def_static("wire_size",
                [](py::bytes b) {
                    std::string s(b);
                    return LoginRejected::wire_size(s.data());
                })
            ;
        c.def_property("pkgLength",
            [](H& h) { return h.msg().pkgLength.to_int(); },
            [](H& h, decltype(h.msg().pkgLength.to_int()) v) { h.msg().pkgLength = v; });
        c.def_property("pkgType",
            [](H& h) { return h.msg().pkgType; },
            [](H& h, PktType v) { h.msg().pkgType = v; });
        c.def_property("code",
            [](H& h) { return h.msg().code; },
            [](H& h, LoginRejectCode v) { h.msg().code = v; });
    }

    // ----- message ServerHeartbeat -----
    {
        using H = Holder<ServerHeartbeat>;
        auto c = py::class_<H>(m, "ServerHeartbeat")
            .def_static("allocate", &H::allocate, py::arg("cap") = DEFAULT_CAP)
            .def_static("from_bytes", &H::from_bytes)
            .def("__bytes__", &H::to_bytes)
            .def("to_bytes", &H::to_bytes)
            .def("size", &H::size)
            .def("capacity", &H::capacity)
            .def_static("fixed_size", []() { return ServerHeartbeat::fixed_size(); })
            .def_static("wire_size",
                [](py::bytes b) {
                    std::string s(b);
                    return ServerHeartbeat::wire_size(s.data());
                })
            ;
        c.def_property("pkgLength",
            [](H& h) { return h.msg().pkgLength.to_int(); },
            [](H& h, decltype(h.msg().pkgLength.to_int()) v) { h.msg().pkgLength = v; });
        c.def_property("pkgType",
            [](H& h) { return h.msg().pkgType; },
            [](H& h, PktType v) { h.msg().pkgType = v; });
    }

    // ----- message ClientHeartbeat -----
    {
        using H = Holder<ClientHeartbeat>;
        auto c = py::class_<H>(m, "ClientHeartbeat")
            .def_static("allocate", &H::allocate, py::arg("cap") = DEFAULT_CAP)
            .def_static("from_bytes", &H::from_bytes)
            .def("__bytes__", &H::to_bytes)
            .def("to_bytes", &H::to_bytes)
            .def("size", &H::size)
            .def("capacity", &H::capacity)
            .def_static("fixed_size", []() { return ClientHeartbeat::fixed_size(); })
            .def_static("wire_size",
                [](py::bytes b) {
                    std::string s(b);
                    return ClientHeartbeat::wire_size(s.data());
                })
            ;
        c.def_property("pkgLength",
            [](H& h) { return h.msg().pkgLength.to_int(); },
            [](H& h, decltype(h.msg().pkgLength.to_int()) v) { h.msg().pkgLength = v; });
        c.def_property("pkgType",
            [](H& h) { return h.msg().pkgType; },
            [](H& h, PktType v) { h.msg().pkgType = v; });
    }

    // ----- message EndOfSession -----
    {
        using H = Holder<EndOfSession>;
        auto c = py::class_<H>(m, "EndOfSession")
            .def_static("allocate", &H::allocate, py::arg("cap") = DEFAULT_CAP)
            .def_static("from_bytes", &H::from_bytes)
            .def("__bytes__", &H::to_bytes)
            .def("to_bytes", &H::to_bytes)
            .def("size", &H::size)
            .def("capacity", &H::capacity)
            .def_static("fixed_size", []() { return EndOfSession::fixed_size(); })
            .def_static("wire_size",
                [](py::bytes b) {
                    std::string s(b);
                    return EndOfSession::wire_size(s.data());
                })
            ;
        c.def_property("pkgLength",
            [](H& h) { return h.msg().pkgLength.to_int(); },
            [](H& h, decltype(h.msg().pkgLength.to_int()) v) { h.msg().pkgLength = v; });
        c.def_property("pkgType",
            [](H& h) { return h.msg().pkgType; },
            [](H& h, PktType v) { h.msg().pkgType = v; });
    }

    // ----- message LoginRequest -----
    {
        using H = Holder<LoginRequest>;
        auto c = py::class_<H>(m, "LoginRequest")
            .def_static("allocate", &H::allocate, py::arg("cap") = DEFAULT_CAP)
            .def_static("from_bytes", &H::from_bytes)
            .def("__bytes__", &H::to_bytes)
            .def("to_bytes", &H::to_bytes)
            .def("size", &H::size)
            .def("capacity", &H::capacity)
            .def_static("fixed_size", []() { return LoginRequest::fixed_size(); })
            .def_static("wire_size",
                [](py::bytes b) {
                    std::string s(b);
                    return LoginRequest::wire_size(s.data());
                })
            ;
        c.def_property("pkgLength",
            [](H& h) { return h.msg().pkgLength.to_int(); },
            [](H& h, decltype(h.msg().pkgLength.to_int()) v) { h.msg().pkgLength = v; });
        c.def_property("pkgType",
            [](H& h) { return h.msg().pkgType; },
            [](H& h, PktType v) { h.msg().pkgType = v; });
        c.def_property("username",
            [](H& h) { return fls_to_string(h.msg().username); },
            [](H& h, const std::string& v) { fls_from_string(h.msg().username, v); });
        c.def_property("password",
            [](H& h) { return fls_to_string(h.msg().password); },
            [](H& h, const std::string& v) { fls_from_string(h.msg().password, v); });
        c.def_property("requestedSession",
            [](H& h) { return fls_to_string(h.msg().requestedSession); },
            [](H& h, const std::string& v) { fls_from_string(h.msg().requestedSession, v); });
        c.def_property("requestedSeqNum",
            [](H& h) { return fls_to_string(h.msg().requestedSeqNum); },
            [](H& h, const std::string& v) { fls_from_string(h.msg().requestedSeqNum, v); });
    }

    // ----- message LogoutRequest -----
    {
        using H = Holder<LogoutRequest>;
        auto c = py::class_<H>(m, "LogoutRequest")
            .def_static("allocate", &H::allocate, py::arg("cap") = DEFAULT_CAP)
            .def_static("from_bytes", &H::from_bytes)
            .def("__bytes__", &H::to_bytes)
            .def("to_bytes", &H::to_bytes)
            .def("size", &H::size)
            .def("capacity", &H::capacity)
            .def_static("fixed_size", []() { return LogoutRequest::fixed_size(); })
            .def_static("wire_size",
                [](py::bytes b) {
                    std::string s(b);
                    return LogoutRequest::wire_size(s.data());
                })
            ;
        c.def_property("pkgLength",
            [](H& h) { return h.msg().pkgLength.to_int(); },
            [](H& h, decltype(h.msg().pkgLength.to_int()) v) { h.msg().pkgLength = v; });
        c.def_property("pkgType",
            [](H& h) { return h.msg().pkgType; },
            [](H& h, PktType v) { h.msg().pkgType = v; });
    }

}


