package eb_lang.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class EBFixedLenghString_Constraints extends BaseConstraintsDescriptor {
  /*package*/ EBFixedLenghString_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.EBFixedLenghString$Ss, initContext);
    record(new Padding_PD(this));
  }

  /*package*/ static final class Padding_PD extends BasePropertyConstraintsDescriptor {
    public Padding_PD(ConstraintsDescriptor container) {
      super(PROPS.padding$ZJtT, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:3627401c-d045-43be-a0d6-b80453db7eba(eb_lang.constraints)", "4485535437959844027"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      if (!(propertyValue.startsWith("'")) || !(propertyValue.endsWith("'"))) {
        return false;
      }
      return (propertyValue.charAt(1) == '\\' && propertyValue.length() == 4) || (propertyValue.charAt(1) != '\\' && propertyValue.length() == 3);
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept EBFixedLenghString$Ss = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e24124b5L, "eb_lang.structure.EBFixedLenghString");
  }

  private static final class PROPS {
    /*package*/ static final SProperty padding$ZJtT = MetaAdapterFactory.getProperty(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e24124b5L, 0x726a4e86e24124b8L, "padding");
  }
}
