package eb_lang.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.scope.ListScope;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class EBMessagePresenceByOptionalBitMember_Constraints extends BaseConstraintsDescriptor {
  /*package*/ EBMessagePresenceByOptionalBitMember_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.EBMessagePresenceByOptionalBitMember$hE, initContext);
    record(new RD1(this));
    record(new RD2(this));
    record(new RD3(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.presence_val$MrAR, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:3627401c-d045-43be-a0d6-b80453db7eba(eb_lang.constraints)", "8968744803451485828");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          List<SNode> statements = new ArrayList<SNode>();
          SNode msg = SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.EBMessage$YV, false, false);
          ListSequence.fromList(statements).addSequence(Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(msg, LINKS.content$vVwC), CONCEPTS.EBMessageEntryMember$fS)).where((it) -> SNodeOperations.isInstanceOf(SLinkOperations.getTarget(it, LINKS.type$zO4N), CONCEPTS.EBEnum$37)));
          ListSequence.fromList(statements).addSequence(Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(msg, LINKS.content$vVwC), CONCEPTS.EBMessagePresenceByValueFieldMember$dj)).where((it) -> SNodeOperations.isInstanceOf(SLinkOperations.getTarget(it, LINKS.type$zO4N), CONCEPTS.EBEnum$37)));

          return ListScope.forNamedElements(statements);
        }
      };
    }
  }
  /*package*/ static final class RD2 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD2(ConstraintsDescriptor container) {
      super(LINKS.target_enum$Mx0e, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:3627401c-d045-43be-a0d6-b80453db7eba(eb_lang.constraints)", "8968744803451500353");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          final int statementContextIndex = SNodeOperations.getIndexInParent(SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.EBTypeStatement$o0, true, false));
          Iterable<SNode> enumStatements = Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.EBProtocol$zC, true, false), LINKS.statements$_5KW), CONCEPTS.EBEnum$37)).where((it) -> SNodeOperations.getIndexInParent(it) < statementContextIndex);
          return ListScope.forNamedElements(enumStatements);
        }
      };
    }
  }
  /*package*/ static final class RD3 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD3(ConstraintsDescriptor container) {
      super(LINKS.mask$Mxff, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:3627401c-d045-43be-a0d6-b80453db7eba(eb_lang.constraints)", "8968744803451586228");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          return ListScope.forNamedElements(SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.target_enum$Mx0e), LINKS.values$_zmn));
        }
      };
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept EBMessagePresenceByOptionalBitMember$hE = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x7c7761e15adb3d7fL, "eb_lang.structure.EBMessagePresenceByOptionalBitMember");
    /*package*/ static final SConcept EBMessage$YV = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a26L, "eb_lang.structure.EBMessage");
    /*package*/ static final SConcept EBMessageEntryMember$fS = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a34L, "eb_lang.structure.EBMessageEntryMember");
    /*package*/ static final SConcept EBEnum$37 = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3d0dL, "eb_lang.structure.EBEnum");
    /*package*/ static final SConcept EBMessagePresenceByValueFieldMember$dj = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x3fa729f2354a0048L, "eb_lang.structure.EBMessagePresenceByValueFieldMember");
    /*package*/ static final SConcept EBTypeStatement$o0 = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3cf3L, "eb_lang.structure.EBTypeStatement");
    /*package*/ static final SConcept EBProtocol$zC = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3cf6L, "eb_lang.structure.EBProtocol");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink presence_val$MrAR = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x7c7761e15adb3d7fL, 0x7c7761e15adb3d80L, "presence_val");
    /*package*/ static final SContainmentLink content$vVwC = MetaAdapterFactory.getContainmentLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a26L, 0x7b5896debde675baL, "content");
    /*package*/ static final SReferenceLink type$zO4N = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x54785f5b332a751cL, 0x3fa729f23447e491L, "type");
    /*package*/ static final SReferenceLink target_enum$Mx0e = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x7c7761e15adb3d7fL, 0x7c7761e15adb3d82L, "target_enum");
    /*package*/ static final SContainmentLink statements$_5KW = MetaAdapterFactory.getContainmentLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3cf6L, 0x726a4e86e23f3cfcL, "statements");
    /*package*/ static final SReferenceLink mask$Mxff = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x7c7761e15adb3d7fL, 0x7c7761e15adb3d83L, "mask");
    /*package*/ static final SContainmentLink values$_zmn = MetaAdapterFactory.getContainmentLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3d0dL, 0x726a4e86e23f3d24L, "values");
  }
}
