package eb_lang_codegen.generator.templates;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import eb_lang.behavior.EBTypeStatement__BehaviorDescriptor;
import eb_lang.behavior.EBInclude__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import eb_lang.behavior.EBIntType__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import eb_lang.behavior.EBMessageEntryMember__BehaviorDescriptor;
import eb_lang.behavior.EBMessage__BehaviorDescriptor;
import eb_lang.behavior.EBImportPrimitive__BehaviorDescriptor;
import eb_lang.behavior.EBMessageMemberVar__BehaviorDescriptor;
import java.util.List;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import java.util.LinkedList;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Iterator;
import java.util.Map;
import jetbrains.mps.generator.impl.query.ReductionRuleCondition;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import jetbrains.mps.generator.template.ReductionRuleQueryContext;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.generator.impl.query.MapRootRuleCondition;
import jetbrains.mps.generator.template.MapRootRuleContext;
import jetbrains.mps.generator.impl.query.SourceNodeQuery;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.Collection;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static boolean rule_Condition_0_0(final BaseMappingRuleContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), PROPS.genType$AtJI) == 0;
  }
  public static boolean rule_Condition_0_1(final BaseMappingRuleContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), PROPS.genType$AtJI) == 1;
  }
  public static boolean rule_Condition_0_2(final BaseMappingRuleContext _context) {
    SPropertyOperations.assign(_context.getNode(), PROPS.genType$AtJI, 0);
    return true;
  }
  public static boolean rule_Condition_0_3(final BaseMappingRuleContext _context) {
    SPropertyOperations.assign(_context.getNode(), PROPS.genType$AtJI, 1);
    return true;
  }
  public static Object propertyMacro_GetValue_0_0(final PropertyMacroContext _context) {
    return "from .common import *\n";
  }
  public static Object propertyMacro_GetValue_0_1(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) == 0) {
      return SPropertyOperations.getString(_context.getNode(), PROPS.value$wDYR) + "\n";
    }
    return "";
  }
  public static Object propertyMacro_GetValue_0_2(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) == 1) {
      return SPropertyOperations.getString(_context.getNode(), PROPS.value$$aYn) + "\n";
    }
    return "";
  }
  public static Object propertyMacro_GetValue_0_3(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) == 0) {
      return String.format("using %s = %s;", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), EBTypeStatement__BehaviorDescriptor.getCppType_id7sFT47Ik3aM.invoke(_context.getNode()));
    }

    return "";
  }
  public static Object propertyMacro_GetValue_0_4(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) == 1) {
      return String.format("%s = %s", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), EBTypeStatement__BehaviorDescriptor.getPyType_id7sFT47Ik3cB.invoke(_context.getNode()));
    }
    return "";
  }
  public static Object propertyMacro_GetValue_0_5(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) == 0) {
      return "//" + SPropertyOperations.getString(_context.getNode(), PROPS.value$wjFT);
    }
    return "# " + SPropertyOperations.getString(_context.getNode(), PROPS.value$wjFT);
  }
  public static Object propertyMacro_GetValue_0_6(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.value$fPEt);
  }
  public static Object propertyMacro_GetValue_0_7(final PropertyMacroContext _context) {
    return "'" + SPropertyOperations.getString(_context.getNode(), PROPS.value$fPcU) + "'";
  }
  public static Object propertyMacro_GetValue_0_8(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) == 0) {
      return EBInclude__BehaviorDescriptor.cpp_include_iduI6saUpFhC.invoke(_context.getNode());
    }
    return EBInclude__BehaviorDescriptor.python_include_iduI6saUpGaM.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetValue_0_9(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 0) {
      return "";
    }

    int nth = 0;
    String field_name = SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.base_member$uj3_), PROPS.name$MnvL);

    for (SNode m : SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), LINKS.base$F2Ny), LINKS.content$vVwC)) {
      if (SPropertyOperations.getString(SNodeOperations.cast(m, CONCEPTS.EBMessageMemberVar$_K), PROPS.name$MnvL) == field_name) {
        break;
      }
      ++nth;
    }

    String skip = "";
    for (int i = 0; i < nth; ++i) {
      skip += "{},";
    }

    String dn = SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.derived$F3h$), PROPS.name$MnvL);
    String field = SPropertyOperations.getString(_context.getNode(), PROPS.field$Acvf);
    if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.base_member$uj3_), LINKS.type$eiFN), CONCEPTS.EBEnum$37)) {
      field = SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.base_member$uj3_), LINKS.type$eiFN), PROPS.name$MnvL) + "::" + field;
    }
    return String.format("%s Create_%s(){return %s{{%s%s}};}", dn, dn, dn, skip, field);

  }
  public static Object propertyMacro_GetValue_0_10(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 1) {
      return "";
    }

    String field = SPropertyOperations.getString(_context.getNode(), PROPS.field$Acvf);
    if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.base_member$uj3_), LINKS.type$eiFN), CONCEPTS.EBEnum$37)) {
      field = SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.base_member$uj3_), LINKS.type$eiFN), PROPS.name$MnvL) + "." + field;
    }

    return String.format("bind_layers(%s, %s, %s=%s)", SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.base$F2Ny), PROPS.name$MnvL), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.derived$F3h$), PROPS.name$MnvL), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.base_member$uj3_), PROPS.name$MnvL), field);
  }
  public static Object propertyMacro_GetValue_0_11(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_0_12(final PropertyMacroContext _context) {
    return String.format("        BitEnumField('%s', %s, %s, %s)", SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.enum$iBH6), PROPS.name$MnvL), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.enum$iBH6), PROPS.name$MnvL) + "." + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.default$Qsog), PROPS.name$MnvL), String.valueOf(SPropertyOperations.getInteger(_context.getNode(), PROPS.length$wbxg)), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.enum$iBH6), PROPS.name$MnvL));
  }
  public static Object propertyMacro_GetValue_0_13(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 0) {
      return "";
    }
    // header
    String header = String.format("struct %s {\n", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL));

    // body
    String body = new String("");
    String indent = new String("    ");
    String indent2 = indent + indent;

    int offset = 0;
    for (SNode member : ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.values$w4DV))) {
      String enum_name = SPropertyOperations.getString(SLinkOperations.getTarget(member, LINKS.enum$iBH6), PROPS.name$MnvL);
      int length = SPropertyOperations.getInteger(member, PROPS.length$wbxg);
      String value = SPropertyOperations.getString(SLinkOperations.getTarget(member, LINKS.default$Qsog), PROPS.name$MnvL);

      body += String.format("%svoid set%s(%s v) {\n%sauto rv = v.raw_value();\n", indent, enum_name, enum_name, indent2);
      if (offset != 0) {
        body += String.format("%srv <<= %s;\n", indent2, offset);
      }
      body += String.format("%sbits &= clear_mask<%s, %s, %s>;\n", indent2, EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$w4bT)), offset, length);
      body += String.format("%sbits |= rv;\n", indent2);
      body += String.format("%s}\n\n", indent);

      body += String.format("%s%s get%s() {\n%sauto v = bits&get_mask<%s, %s, %s>;\n", indent, enum_name, enum_name, indent2, EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$w4bT)), offset, length);
      if (offset != 0) {
        body += String.format("%sv >>= %s;\n", indent2, offset);
      }
      body += String.format("%sreturn %s(v);\n", indent2, EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$w4bT)));
      body += String.format("%s}\n\n", indent);

      offset += length;

    }

    body += String.format("%svoid clear() {\n%s%sbits = 0;\n%s}\n", indent, indent, indent, indent);
    body += String.format("%s%s bits;\n", indent, EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$w4bT)));

    body += " };\n\n";
    // out

    String out_str = new String("");

    out_str += String.format("template<typename ostreamT>\nostreamT& operator<<(ostreamT& os, const %s& v) {\n", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL));

    int idx = 0;
    for (SNode member : ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.values$w4DV))) {
      String enum_name = SPropertyOperations.getString(SLinkOperations.getTarget(member, LINKS.enum$iBH6), PROPS.name$MnvL);
      String sep = "|";
      if (idx++ == 0) {
        sep = "";
      }
      out_str += String.format("%sos << \"%s%s=\" << v.get%s();\n", indent, sep, enum_name, enum_name);
    }

    out_str += String.format("}");

    return header + body + out_str;
  }
  public static Object propertyMacro_GetValue_0_14(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 1) {
      return "";
    }

    String header = String.format("class %s(Packet):\n     fields_desc = [\n", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL));
    String end = new String("    ]");

    for (SNode m : SLinkOperations.getChildren(_context.getNode(), LINKS.values$w4DV)) {
      String item = String.format("        BitEnumField('%s', %s, %s, %s)\n", SPropertyOperations.getString(SLinkOperations.getTarget(m, LINKS.enum$iBH6), PROPS.name$MnvL), SPropertyOperations.getString(SLinkOperations.getTarget(m, LINKS.enum$iBH6), PROPS.name$MnvL) + "." + SPropertyOperations.getString(SLinkOperations.getTarget(m, LINKS.default$Qsog), PROPS.name$MnvL), String.valueOf(SPropertyOperations.getInteger(m, PROPS.length$wbxg)), SPropertyOperations.getString(SLinkOperations.getTarget(m, LINKS.enum$iBH6), PROPS.name$MnvL));

      header += item;
    }

    return header + end;
  }
  public static Object propertyMacro_GetValue_0_15(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 0) {
      return "";
    }

    String body = String.format("struct %s {\n", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL));
    String indent = new String("    ");
    body += String.format("%susing value_type = %s;\n", indent, EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)));
    body += String.format("%senum Enum : value_type {\n", indent);
    for (SNode kv : ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.values$_zmn))) {
      String v = new String("");
      if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(kv, LINKS.value$_yQp), CONCEPTS.EBCharLiteral$iB)) {
        v = String.format("'%s'", SPropertyOperations.getString(SNodeOperations.cast(SLinkOperations.getTarget(kv, LINKS.value$_yQp), CONCEPTS.EBCharLiteral$iB), PROPS.value$fPcU));
      } else {
        v = SPropertyOperations.getString(SNodeOperations.cast(SLinkOperations.getTarget(kv, LINKS.value$_yQp), CONCEPTS.EBNumberLiteral$i8), PROPS.value$fPEt);
      }

      body += String.format("%s%s%s = %s,\n", indent, indent, SPropertyOperations.getString(kv, PROPS.name$MnvL), v);
    }
    body += String.format("%s};\n", indent);
    body += String.format("%sstatic constexpr const size_t size = %s;\n", indent, (int) EBIntType__BehaviorDescriptor.size_id7qxjCwPtApr.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)));
    body += String.format("%sstatic constexpr const char* name() {return \"%s\";}\n", indent, SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL));

    {
      String min_list = new String("");

      for (SNode kv : ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.values$_zmn))) {
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(kv, LINKS.value$_yQp), CONCEPTS.EBCharLiteral$iB)) {
          min_list += String.format("static_cast<%s>('%s'), ", EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)), SPropertyOperations.getString(SNodeOperations.cast(SLinkOperations.getTarget(kv, LINKS.value$_yQp), CONCEPTS.EBCharLiteral$iB), PROPS.value$fPcU));
        } else {
          min_list += String.format("static_cast<%s>(%s), ", EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)), SPropertyOperations.getString(SNodeOperations.cast(SLinkOperations.getTarget(kv, LINKS.value$_yQp), CONCEPTS.EBNumberLiteral$i8), PROPS.value$fPEt));
        }
      }
      body += String.format("%sstatic constexpr const value_type min_value = std::min<value_type>({%s});\n", indent, min_list);
    }
    {
      String max_list = new String("");

      for (SNode kv : ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.values$_zmn))) {
        if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(kv, LINKS.value$_yQp), CONCEPTS.EBCharLiteral$iB)) {
          max_list += String.format("static_cast<%s>('%s'), ", EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)), SPropertyOperations.getString(SNodeOperations.cast(SLinkOperations.getTarget(kv, LINKS.value$_yQp), CONCEPTS.EBCharLiteral$iB), PROPS.value$fPcU));
        } else {
          max_list += String.format("static_cast<%s>(%s), ", EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)), SPropertyOperations.getString(SNodeOperations.cast(SLinkOperations.getTarget(kv, LINKS.value$_yQp), CONCEPTS.EBNumberLiteral$i8), PROPS.value$fPEt));
        }
      }
      body += String.format("%sstatic constexpr const value_type max_value = std::max<value_type>({%s});\n", indent, max_list);
    }
    body += String.format("%sconstexpr %s():value_{max_value} {}\n", indent, SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL));
    body += String.format("%sconstexpr explicit %s(%s v):value_{v} {}\n", indent, SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)));
    body += String.format("%sconstexpr %s(Enum v):value_{v} {}\n", indent, SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL));
    body += String.format("%sconstexpr const bool operator==(const %s& rhs) const {return value_ == rhs.value_;}\n", indent, SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)), EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)));
    body += String.format("%sconstexpr const bool operator!=(const %s& rhs) const {return value_ != rhs.value_;}\n", indent, SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)), EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)));
    body += String.format("%sconstexpr const Enum value() const {return value_;}\n", indent);
    body += String.format("%sconstexpr const %s raw_value() const {return static_cast<%s>(value_);}\n", indent, EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)), EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)));
    body += String.format("%sconstexpr const void raw_value(%s v) {value_ = Enum(v);}\n", indent, EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)));
    body += String.format("%sconstexpr const void set(Enum v) {value_ = v;}\n", indent, EBIntType__BehaviorDescriptor.cppName_id9WwCMYBSZJ.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl)));

    body += String.format("%sconstexpr const int length() const {return sizeof(value_);}\n", indent);

    {
      String view_list = new String("");

      for (SNode kv : ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.values$_zmn))) {
        view_list += String.format("%s%s%scase Enum::%s: return \"%s\";\n", indent, indent, indent, SPropertyOperations.getString(kv, PROPS.name$MnvL), SPropertyOperations.getString(kv, PROPS.name$MnvL));
      }

      body += String.format("%sconstexpr const std::string_view to_string_view() const {\n%s%sswitch(value_) {\n%s%s%s}\n%s%sreturn \"\";\n%s}\n", indent, indent, indent, view_list, indent, indent, indent, indent, indent);
    }
    body += indent + "Enum value_{max_value};\n};\n\n";

    body += String.format("template <typename ostreamT>\ninline ostreamT& operator<<(ostreamT& os, const %s& v){\n    os << v.to_string_view();\n    return os;\n}\n", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL));

    return body;
  }
  public static Object propertyMacro_GetValue_0_16(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 1) {
      return "";
    }

    String type = new String("int");
    if (SConceptOperations.conceptAlias(SNodeOperations.getConcept(SLinkOperations.getTarget(_context.getNode(), LINKS.type$_ySl))) == "char_ebt") {
      type = "str";
    }

    String body = String.format("class %s(%s, Enum):\n", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), type);
    for (SNode p : SLinkOperations.getChildren(_context.getNode(), LINKS.values$_zmn)) {
      if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(p, LINKS.value$_yQp), CONCEPTS.EBCharLiteral$iB)) {
        body += String.format("    %s = '%s'\n", SPropertyOperations.getString(p, PROPS.name$MnvL), SPropertyOperations.getString(SNodeOperations.cast(SLinkOperations.getTarget(p, LINKS.value$_yQp), CONCEPTS.EBCharLiteral$iB), PROPS.value$fPcU));
      } else {
        body += String.format("    %s = %s\n", SPropertyOperations.getString(p, PROPS.name$MnvL), SPropertyOperations.getString(SNodeOperations.cast(SLinkOperations.getTarget(p, LINKS.value$_yQp), CONCEPTS.EBNumberLiteral$i8), PROPS.value$fPEt));
      }
    }

    return body;
  }
  public static Object propertyMacro_GetValue_0_17(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 0) {
      return "";
    }

    String defaultValue = EBMessageEntryMember__BehaviorDescriptor.fmtCppDefault_id7hSmxNQ32$j.invoke(_context.getNode());
    if ((defaultValue != null && defaultValue.length() > 0)) {
      defaultValue = String.format("{%s}", defaultValue);
    } else {
      defaultValue = "";
    }

    boolean has_var_before = false;
    SNode pre_node = (SNode) SNodeOperations.getPrevSibling(_context.getNode());
    SNode direct_pre_node = pre_node;
    while ((pre_node != null)) {
      if (SNodeOperations.isInstanceOf(pre_node, CONCEPTS.EBMessageBlockMember$o) || SNodeOperations.isInstanceOf(pre_node, CONCEPTS.EBMessagePresenceFieldMember$Z)) {
        has_var_before = true;
        break;
      }
      if (SNodeOperations.isInstanceOf(pre_node, CONCEPTS.EBMessageEntryMember$fS) && SNodeOperations.isInstanceOf(SLinkOperations.getTarget(SNodeOperations.cast(pre_node, CONCEPTS.EBMessageEntryMember$fS), LINKS.type$eiFN), CONCEPTS.EBMessage$YV) && (boolean) EBMessage__BehaviorDescriptor.isNotFixedLength_id4Xeby11878t.invoke(SNodeOperations.cast(SLinkOperations.getTarget(SNodeOperations.cast(pre_node, CONCEPTS.EBMessageEntryMember$fS), LINKS.type$eiFN), CONCEPTS.EBMessage$YV))) {
        has_var_before = true;
        break;
      }
      pre_node = ((SNode) SNodeOperations.getPrevSibling(pre_node));
    }

    if (has_var_before) {
      return String.format("FloatingRef<%1$s> %2$s() {return FloatingRef<%1$s>(%3$s().end());}", SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), CONCEPTS.EBMessageEntryMember$fS), LINKS.type$eiFN), PROPS.name$MnvL), SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), SPropertyOperations.getString(direct_pre_node, PROPS.name$MnvL));

    }

    return String.format("%s %s%s;", SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), PROPS.name$MnvL), SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), defaultValue);
  }
  public static Object propertyMacro_GetValue_0_18(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 1) {
      return "";
    }
    if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), CONCEPTS.EBEnum$37)) {
      String pyTypeName = EBTypeStatement__BehaviorDescriptor.getPyType_id7sFT47Ik3cB.invoke(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), CONCEPTS.EBEnum$37));
      String enumName = SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), PROPS.name$MnvL);
      String fieldName = SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
      String defaultValue = SPropertyOperations.getString(_context.getNode(), PROPS.default$w7ZO);
      if ((defaultValue == null || defaultValue.length() == 0)) {
        defaultValue = String.format("%s.%s", enumName, SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getChildren(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), CONCEPTS.EBEnum$37), LINKS.values$_zmn)).last(), PROPS.name$MnvL));
      }
      return String.format("    %s(\"%s\", %s, %s)", pyTypeName, fieldName, defaultValue, enumName);

    } else if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), CONCEPTS.EBImportPrimitive$gU)) {
      if (isNotEmptyString(SPropertyOperations.getString(_context.getNode(), PROPS.counterOf$_QEd)) && SNodeOperations.isInstanceOf(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), CONCEPTS.EBImportPrimitive$gU), LINKS.type$zVeR), CONCEPTS.EBIntType$ej)) {
        String fmt = EBIntType__BehaviorDescriptor.fmt_id4GpIFxqoQnK.invoke(SNodeOperations.cast(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), CONCEPTS.EBImportPrimitive$gU), LINKS.type$zVeR), CONCEPTS.EBIntType$ej));
        return String.format("    FieldLenField(\"%s\", 0, fmt=\"%s\", count_of=\"%s\")", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), fmt, SPropertyOperations.getString(_context.getNode(), PROPS.counterOf$_QEd));
      }

      String defaultValue = SPropertyOperations.getString(_context.getNode(), PROPS.default$w7ZO);
      if ((defaultValue == null || defaultValue.length() == 0)) {
        defaultValue = EBImportPrimitive__BehaviorDescriptor.getPyDefault_id3_eh5mZVois.invoke(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), CONCEPTS.EBImportPrimitive$gU));
      }
      return String.format("    %s(\"%s\", %s)", SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), PROPS.name$MnvL), SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), defaultValue);
    } else if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), CONCEPTS.EBBitField$xS)) {
      String pyTypeName = EBTypeStatement__BehaviorDescriptor.getPyType_id7sFT47Ik3cB.invoke(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), CONCEPTS.EBBitField$xS));
      String defaultValue = SPropertyOperations.getString(_context.getNode(), PROPS.default$w7ZO);
      if ((defaultValue == null || defaultValue.length() == 0)) {
        defaultValue = "0";
      }
      return String.format("    %s(\"%s\", %s, %s)", pyTypeName, SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), defaultValue, SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), PROPS.name$MnvL));
    } else if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), CONCEPTS.EBMessage$YV)) {
      return String.format("    PacketField(\"%s\", \"\", %s)", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN), PROPS.name$MnvL));
    }

    return "Unsupported type " + SConceptOperations.conceptAlias(SNodeOperations.getConcept(SLinkOperations.getTarget(_context.getNode(), LINKS.type$eiFN)));


  }
  public static Object propertyMacro_GetValue_0_19(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 0) {
      return "";
    }

    SNode pre_node = (SNode) SNodeOperations.getPrevSibling(_context.getNode());
    while ((pre_node != null) && !(SNodeOperations.isInstanceOf(pre_node, CONCEPTS.EBMessageMemberVar$_K))) {
      pre_node = (SNode) SNodeOperations.getPrevSibling(pre_node);
    }

    if ((pre_node == null)) {
      // this node is first EBMessageMemberVar
      return String.format("    BlockRef<%s> %s() {return BlockRef<%s>(begin()+size(), %s);}", SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$kyUc), PROPS.name$MnvL), SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$kyUc), PROPS.name$MnvL), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.counter$kzoe), PROPS.name$MnvL));

    } else {
      // indirect pre_node is EBMessageMemberVar
      SNode pre_var = (SNode) pre_node;
      if ((boolean) EBMessageMemberVar__BehaviorDescriptor.isNotFixedLength_id5hSnPGNaBkU.invoke(pre_var)) {
        return String.format("    BlockRef<%s> %s() {return BlockRef<%s>(%s().end(), %s);}", SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$kyUc), PROPS.name$MnvL), SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$kyUc), PROPS.name$MnvL), SPropertyOperations.getString(pre_var, PROPS.name$MnvL), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.counter$kzoe), PROPS.name$MnvL));

      } else {
        return String.format("    BlockRef<%s> %s() {return BlockRef<%s>(begin()+size(), %s);}", SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$kyUc), PROPS.name$MnvL), SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$kyUc), PROPS.name$MnvL), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.counter$kzoe), PROPS.name$MnvL));

      }
    }

  }
  public static Object propertyMacro_GetValue_0_20(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 1) {
      return "";
    }
    return String.format("        PacketListField(\"%s\", None, %s, count_from=lambda pkt:pkt.%s", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$kyUc), PROPS.name$MnvL), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.counter$kzoe), PROPS.name$MnvL));

  }
  public static Object propertyMacro_GetValue_0_21(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 0) {
      return "";
    }

    SNode pre_node = (SNode) SNodeOperations.getPrevSibling(_context.getNode());
    while ((pre_node != null) && !(SNodeOperations.isInstanceOf(pre_node, CONCEPTS.EBMessageMemberVar$_K))) {
      pre_node = (SNode) SNodeOperations.getPrevSibling(pre_node);
    }

    String presenceMapString = EBTypeStatement__BehaviorDescriptor.getCppType_id7sFT47Ik3aM.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.presence_map$Zjwo), LINKS.type$eiFN));

    if ((pre_node == null)) {
      // this node is first EBMessageMemberVar

      return String.format("    OptionalRef<%1$s, %5$s> %2$s() {return OptionalRef<%1$s, %5$s>(begin()+size(), %3$s, %4$s);}", SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$Zjhn), PROPS.name$MnvL), SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), SLinkOperations.getTarget(_context.getNode(), LINKS.presence_map$Zjwo), SPropertyOperations.getString(_context.getNode(), PROPS.pos$ZoEI), presenceMapString);

    } else {
      // indirect pre_node is EBMessageMemberVar
      SNode pre_var = (SNode) pre_node;
      if ((boolean) EBMessageMemberVar__BehaviorDescriptor.isNotFixedLength_id5hSnPGNaBkU.invoke(pre_var)) {
        return String.format("    OptionalRef<%1$s, %6$s> %2$s() {return OptionalRef<%1$s, %6$s>(%3$s().end(), %4$s, %5$s);}", SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$Zjhn), PROPS.name$MnvL), SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), SPropertyOperations.getString(pre_var, PROPS.name$MnvL), SLinkOperations.getTarget(_context.getNode(), LINKS.presence_map$Zjwo), SPropertyOperations.getString(_context.getNode(), PROPS.pos$ZoEI), presenceMapString);

      } else {
        return String.format("    OptionalRef<%1$s, %5$s> %2$s() {return OptionalRef<%1$s, %5$s>(begin()+size(), %3$s, %4$s);}", SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$Zjhn), PROPS.name$MnvL), SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), SLinkOperations.getTarget(_context.getNode(), LINKS.presence_map$Zjwo), SPropertyOperations.getString(_context.getNode(), PROPS.pos$ZoEI), presenceMapString);

      }
    }

  }
  public static Object propertyMacro_GetValue_0_22(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 1) {
      return "";
    }
    if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.type$Zjhn), CONCEPTS.EBEnum$37)) {
      String pyTypeName = EBTypeStatement__BehaviorDescriptor.getPyType_id7sFT47Ik3cB.invoke(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), LINKS.type$Zjhn), CONCEPTS.EBEnum$37));
      String enumName = SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.type$Zjhn), PROPS.name$MnvL);
      String fieldName = SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
      String defaultValue = String.format("%s.%s", enumName, SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getChildren(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), LINKS.type$Zjhn), CONCEPTS.EBEnum$37), LINKS.values$_zmn)).last(), PROPS.name$MnvL));

      return String.format("        ConditionalField(%s(\"%s\", %s, %s), lambda pkt:pkt.%s&(1<<(%s)))", pyTypeName, SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), defaultValue, enumName, SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.presence_map$Zjwo), PROPS.name$MnvL), SPropertyOperations.getString(_context.getNode(), PROPS.pos$ZoEI));
    } else if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.type$Zjhn), CONCEPTS.EBImportPrimitive$gU)) {
      String defaultValue = EBImportPrimitive__BehaviorDescriptor.getPyDefault_id3_eh5mZVois.invoke(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), LINKS.type$Zjhn), CONCEPTS.EBImportPrimitive$gU));

      return String.format("        ConditionalField(%s(\"%s\", %s), lambda pkt:pkt.%s&(1<<(%s)))", SLinkOperations.getTarget(_context.getNode(), LINKS.type$Zjhn), SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), defaultValue, SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.presence_map$Zjwo), PROPS.name$MnvL), SPropertyOperations.getString(_context.getNode(), PROPS.pos$ZoEI));
    } else if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.type$Zjhn), CONCEPTS.EBMessage$YV)) {
      return String.format("        ConditionalField(PacketField(\"%s\", None, %s), lambda pkt:pkt.%s&(1<<(%s)))", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), SLinkOperations.getTarget(_context.getNode(), LINKS.type$Zjhn), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.presence_map$Zjwo), PROPS.name$MnvL), SPropertyOperations.getString(_context.getNode(), PROPS.pos$ZoEI));
    }

    return String.format("        ConditionalField(%s, lambda pkt:pkt.%s&(1<<(%s)))", SLinkOperations.getTarget(_context.getNode(), LINKS.type$Zjhn), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.presence_map$Zjwo), PROPS.name$MnvL), SPropertyOperations.getString(_context.getNode(), PROPS.pos$ZoEI));

  }
  public static Object propertyMacro_GetValue_0_23(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 0) {
      return "";
    }
    return "#pragma pack(1)\n";
  }
  public static Object propertyMacro_GetValue_0_24(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) == 0) {
      String base = "";
      if ((SLinkOperations.getTarget(_context.getNode(), LINKS.base$LfNH) != null)) {
        base = " : " + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.base$LfNH), PROPS.name$MnvL);
      }
      return String.format("struct %s%s {\n", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), base);
    } else {
      return String.format("class %s(Packet):\n    name = '%s'\n    fields_desc = [\n", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL));
    }
  }
  public static Object propertyMacro_GetValue_0_25(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 0) {
      return "";
    }

    String begin = "char* begin() {return reinterpret_cast<char*>(this);}";
    String end = "char* end() {return begin()+length();}";
    String size = String.format("size_t size() {return sizeof(%s);}", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL));
    String length = "size_t length() {return size();}";
    if ((boolean) EBMessage__BehaviorDescriptor.isNotFixedLength_id4Xeby11878t.invoke(_context.getNode())) {
      // the last member must be a variable length member
      SNode last = ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.content$vVwC)).last();
      while ((last != null) && !(SNodeOperations.isInstanceOf(last, CONCEPTS.EBMessageMemberVar$_K))) {
        last = ((SNode) SNodeOperations.getPrevSibling(last));
      }
      SNode last_var = (SNode) last;
      length = String.format("size_t length() {return %s().end()-begin();}", SPropertyOperations.getString(last_var, PROPS.name$MnvL));

    }

    return String.format("    %s\n    %s\n    %s\n    %s\n", begin, end, size, length);
  }
  public static Object propertyMacro_GetValue_0_26(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) == 0) {
      return "};\n";
    } else {
      return "    ]\n";
    }
  }
  public static Object propertyMacro_GetValue_0_27(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 0) {
      return "";
    }
    return "#pragma pack()\n";
  }
  public static Object propertyMacro_GetValue_0_28(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 0) {
      return "";
    }

    String name = SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
    String size = String.valueOf(SPropertyOperations.getInteger(_context.getNode(), PROPS.size$1BwP));
    if (SPropertyOperations.getInteger(_context.getNode(), PROPS.size$1BwP) != 0) {
      return "static_assert(sizeof(" + name + ") == " + size + ", \"Bad message size.\")\n";
    }
    return "";
  }
  public static Object propertyMacro_GetValue_0_29(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(SNodeOperations.getNodeAncestor(_context.getNode(), CONCEPTS.EBProtocol$zC, false, false), PROPS.genType$AtJI) != 0) {
      return "";
    }

    List<SNode> msgList = ListSequence.fromList(new ArrayList<SNode>());
    ListSequence.fromList(msgList).insertElement(0, _context.getNode());
    SNode currentNode = _context.getNode();
    while ((SLinkOperations.getTarget(currentNode, LINKS.base$LfNH) != null)) {
      ListSequence.fromList(msgList).insertElement(0, SLinkOperations.getTarget(currentNode, LINKS.base$LfNH));
      currentNode = SLinkOperations.getTarget(currentNode, LINKS.base$LfNH);
    }

    String asString = String.format("inline std::ostream& operator<<(std::ostream& os, const %s& msg) {", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL));

    if ((SLinkOperations.getTarget(_context.getNode(), LINKS.base$LfNH) != null)) {
      asString += String.format("\n    os << static_cast<const %s&>(msg);", SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.base$LfNH), PROPS.name$MnvL));
    }
    asString += "\n    os ";

    for (SNode ele : ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.content$vVwC))) {
      if (SNodeOperations.isInstanceOf(ele, CONCEPTS.EBMessageMemberVar$_K)) {
        if (!(SNodeOperations.isInstanceOf(ele, CONCEPTS.EBMessageEntryMember$fS))) {
          asString += String.format("<< \"%2$s=\" << const_cast<%1$s&>(msg).%2$s() << \";\"\n       ", SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL), SPropertyOperations.getString(SNodeOperations.cast(ele, CONCEPTS.EBMessageMemberVar$_K), PROPS.name$MnvL));
        } else {
          asString += String.format("<< \"%1$s=\" << msg.%1$s << \";\"\n       ", SPropertyOperations.getString(SNodeOperations.cast(ele, CONCEPTS.EBMessageMemberVar$_K), PROPS.name$MnvL));
        }
      }
    }

    asString += "; return os;\n}\n";
    return asString;
  }
  public static Object propertyMacro_GetValue_1_0(final PropertyMacroContext _context) {
    return SModelOperations.getModelName(_context.getInputModel());

  }
  public static Object propertyMacro_GetValue_2_0(final PropertyMacroContext _context) {
    return SModelOperations.getModelName(_context.getInputModel());
  }
  public static SNode sourceNodeQuery_0_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.value$_yQp);
  }
  public static Iterable<SNode> sourceNodesQuery_0_0(final SourceSubstituteMacroNodesContext _context) {
    // cpp
    List<SNode> slist = ListSequence.fromList(new LinkedList<SNode>());
    boolean typedAlreadyDefined = false;
    SNode once = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e24169c4L, "eb_lang.structure.EBCPP"));
    SPropertyOperations.assign(once, PROPS.value$wDYR, "#pragma once");
    ListSequence.fromList(slist).addElement(once);
    SNode include_common = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e24169c4L, "eb_lang.structure.EBCPP"));
    SPropertyOperations.assign(include_common, PROPS.value$wDYR, "#include \"eb_common.hpp\"\n");
    ListSequence.fromList(slist).addElement(include_common);

    List<SNode> ilist = ListSequence.fromList(new LinkedList<SNode>());
    for (SNode statement : ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.statements$_5KW))) {
      if (SNodeOperations.isInstanceOf(statement, CONCEPTS.EBInclude$_h)) {
        ListSequence.fromList(ilist).addElement((SNode) statement);
      }
    }

    for (SNode statement : ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.statements$_5KW))) {
      if (SNodeOperations.isInstanceOf(statement, CONCEPTS.EBTypeStatement$o0)) {
        if (!(typedAlreadyDefined)) {
          SNode ns_start = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e24169c4L, "eb_lang.structure.EBCPP"));
          SPropertyOperations.assign(ns_start, PROPS.value$wDYR, "namespace " + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL) + " {");
          ListSequence.fromList(slist).addElement(ns_start);

          SNode common_namespace = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e24169c4L, "eb_lang.structure.EBCPP"));
          SPropertyOperations.assign(common_namespace, PROPS.value$wDYR, "using namespace EB::common;\n");
          ListSequence.fromList(slist).addElement(common_namespace);

          for (SNode include : ListSequence.fromList(ilist)) {
            SNode cpp_include = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e24169c4L, "eb_lang.structure.EBCPP"));
            SPropertyOperations.assign(cpp_include, PROPS.value$wDYR, "using namespace " + SPropertyOperations.getString(SLinkOperations.getTarget(include, LINKS.protocol$v5qn), PROPS.name$MnvL) + ";");
            ListSequence.fromList(slist).addElement(cpp_include);
          }
        }
        typedAlreadyDefined = true;
      }
      ListSequence.fromList(slist).addElement(statement);
    }

    SNode ns_end = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e24169c4L, "eb_lang.structure.EBCPP"));
    SPropertyOperations.assign(ns_end, PROPS.value$wDYR, "} // end of namespace " + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL));
    ListSequence.fromList(slist).addElement(ns_end);

    return slist;
  }
  public static Iterable<SNode> sourceNodesQuery_0_1(final SourceSubstituteMacroNodesContext _context) {
    // python
    List<SNode> slist = ListSequence.fromList(new LinkedList<SNode>());
    for (SNode statement : ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.statements$_5KW))) {
      if (SNodeOperations.isInstanceOf(statement, CONCEPTS.EBMessage$YV)) {
        // clear counterOf value
        {
          Iterator<SNode> member_it = ListSequence.fromList(SLinkOperations.getChildren(SNodeOperations.cast(statement, CONCEPTS.EBMessage$YV), LINKS.content$vVwC)).iterator();
          SNode member_var;
          while (member_it.hasNext()) {
            member_var = member_it.next();
            if (SNodeOperations.isInstanceOf(member_var, CONCEPTS.EBMessageEntryMember$fS)) {
              SPropertyOperations.assign(SNodeOperations.cast(member_var, CONCEPTS.EBMessageEntryMember$fS), PROPS.counterOf$_QEd, null);
            }
          }
        }

        // set counterOf value
        {
          Iterator<SNode> member_it = ListSequence.fromList(SLinkOperations.getChildren(SNodeOperations.cast(statement, CONCEPTS.EBMessage$YV), LINKS.content$vVwC)).iterator();
          SNode member_var;
          while (member_it.hasNext()) {
            member_var = member_it.next();
            if (SNodeOperations.isInstanceOf(member_var, CONCEPTS.EBMessageBlockMember$o)) {
              SPropertyOperations.assign(SLinkOperations.getTarget(SNodeOperations.cast(member_var, CONCEPTS.EBMessageBlockMember$o), LINKS.counter$kzoe), PROPS.counterOf$_QEd, SPropertyOperations.getString(SNodeOperations.cast(member_var, CONCEPTS.EBMessageBlockMember$o), PROPS.name$MnvL));
            }
          }
        }
      }
      ListSequence.fromList(slist).addElement(statement);
    }

    return slist;

  }
  public static Iterable<SNode> sourceNodesQuery_0_2(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.content$vVwC);
  }
  public static Iterable<SNode> sourceNodesQuery_1_0(final SourceSubstituteMacroNodesContext _context) {
    return SModelOperations.roots(_context.getInputModel(), CONCEPTS.EBProtocol$zC);
  }
  public static Iterable<SNode> sourceNodesQuery_2_0(final SourceSubstituteMacroNodesContext _context) {
    return SModelOperations.roots(_context.getInputModel(), CONCEPTS.EBProtocol$zC);
  }
  private final Map<String, ReductionRuleCondition> rrcMethods = new HashMap<String, ReductionRuleCondition>();
  {
    int i = 0;
    rrcMethods.put("3463732535972194386", new RRC(i++));
    rrcMethods.put("5619175737677318947", new RRC(i++));
  }
  @Override
  @NotNull
  public ReductionRuleCondition getReductionRuleCondition(@NotNull QueryKey identity) {
    ReductionRuleCondition query = identity.forTemplateNode(rrcMethods);
    return (query != null ? query : super.getReductionRuleCondition(identity));
  }
  private static class RRC implements ReductionRuleCondition {
    private final int methodKey;
    public RRC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(ReductionRuleQueryContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.rule_Condition_0_0(ctx);
        case 1:
          return QueriesGenerated.rule_Condition_0_1(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for rule %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, MapRootRuleCondition> mrrcMethods = new HashMap<String, MapRootRuleCondition>();
  {
    int i = 0;
    mrrcMethods.put("5619175737672414419", new MRRC(i++));
    mrrcMethods.put("5619175737672652992", new MRRC(i++));
  }
  @Override
  @NotNull
  public MapRootRuleCondition getMapRootRuleCondition(@NotNull QueryKey identity) {
    MapRootRuleCondition query = identity.forTemplateNode(mrrcMethods);
    return (query != null ? query : super.getMapRootRuleCondition(identity));
  }
  private static class MRRC implements MapRootRuleCondition {
    private final int methodKey;
    public MRRC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(@NotNull MapRootRuleContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.rule_Condition_0_2(ctx);
        case 1:
          return QueriesGenerated.rule_Condition_0_3(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for rule %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, SourceNodeQuery> snqMethods = new HashMap<String, SourceNodeQuery>();
  {
    int i = 0;
    snqMethods.put("8717146646091307986", new SNQ(i++));
  }
  @NotNull
  @Override
  public SourceNodeQuery getSourceNodeQuery(@NotNull QueryKey identity) {
    SourceNodeQuery query = identity.forFunctionNode(snqMethods);
    return (query != null ? query : super.getSourceNodeQuery(identity));
  }
  private static class SNQ implements SourceNodeQuery {
    private final int methodKey;
    public SNQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Nullable
    public SNode evaluate(@NotNull SourceSubstituteMacroNodeContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.sourceNodeQuery_0_0(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("3125123739803227906", new SNsQ(i++));
    snsqMethods.put("5619175737677318991", new SNsQ(i++));
    snsqMethods.put("5619175737692848587", new SNsQ(i++));
    snsqMethods.put("8717146646090831958", new SNsQ(i++));
    snsqMethods.put("1239916309617336793", new SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    SourceNodesQuery query = identity.forFunctionNode(snsqMethods);
    return (query != null ? query : super.getSourceNodesQuery(identity));
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_0_0(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_0_1(ctx));
        case 2:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_0_2(ctx));
        case 3:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_0(ctx));
        case 4:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_2_0(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("5619175737677318951", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "header"));
    pvqMethods.put("101094168084350895", new PVQ(i++, MetaAdapterFactory.getProperty(0xcf681fc9c7984f89L, 0xaf38ba3c0ac342d9L, 0x692d8403c84c5eb9L, 0x692d8403c84cb291L, "text"), "cpp"));
    pvqMethods.put("1239916309617376666", new PVQ(i++, MetaAdapterFactory.getProperty(0xcf681fc9c7984f89L, 0xaf38ba3c0ac342d9L, 0x692d8403c84c5eb9L, 0x692d8403c84cb291L, "text"), "py"));
    pvqMethods.put("5619175737673146108", new PVQ(i++, MetaAdapterFactory.getProperty(0xcf681fc9c7984f89L, 0xaf38ba3c0ac342d9L, 0x692d8403c84c5eb9L, 0x692d8403c84cb291L, "text"), "cpp"));
    pvqMethods.put("5619175737673147774", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "py"));
    pvqMethods.put("101094168084399908", new PVQ(i++, MetaAdapterFactory.getProperty(0xcf681fc9c7984f89L, 0xaf38ba3c0ac342d9L, 0x692d8403c84c5eb9L, 0x692d8403c84cb291L, "text"), " "));
    pvqMethods.put("8717146646091253482", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), " "));
    pvqMethods.put("8717146646091255669", new PVQ(i++, MetaAdapterFactory.getProperty(0xcf681fc9c7984f89L, 0xaf38ba3c0ac342d9L, 0x692d8403c84c5eb9L, 0x692d8403c84cb291L, "text"), " "));
    pvqMethods.put("553408128354811797", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "cpp"));
    pvqMethods.put("1399011618627711132", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "cpp"));
    pvqMethods.put("5619175737679011115", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "py"));
    pvqMethods.put("8717146646091303196", new PVQ(i++, MetaAdapterFactory.getProperty(0xcf681fc9c7984f89L, 0xaf38ba3c0ac342d9L, 0x692d8403c84c5eb9L, 0x692d8403c84cb291L, "text"), "key"));
    pvqMethods.put("5619175737679632263", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "py"));
    pvqMethods.put("5619175737680006755", new PVQ(i++, MetaAdapterFactory.getProperty(0xcf681fc9c7984f89L, 0xaf38ba3c0ac342d9L, 0x692d8403c84c5eb9L, 0x692d8403c84cb291L, "text"), "cpp"));
    pvqMethods.put("5619175737680657759", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "py"));
    pvqMethods.put("5619175737682731980", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "cpp"));
    pvqMethods.put("5619175737682732408", new PVQ(i++, MetaAdapterFactory.getProperty(0xcf681fc9c7984f89L, 0xaf38ba3c0ac342d9L, 0x692d8403c84c5eb9L, 0x692d8403c84cb291L, "text"), "py"));
    pvqMethods.put("6284687853305109675", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "cpp"));
    pvqMethods.put("5619175737692404647", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "py"));
    pvqMethods.put("5178973056555875903", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "cpp"));
    pvqMethods.put("5619175737692415593", new PVQ(i++, MetaAdapterFactory.getProperty(0xcf681fc9c7984f89L, 0xaf38ba3c0ac342d9L, 0x692d8403c84c5eb9L, 0x692d8403c84cb291L, "text"), "py"));
    pvqMethods.put("7035066850818182175", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "cpp"));
    pvqMethods.put("5619175737692422011", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "py"));
    pvqMethods.put("5619175737692848546", new PVQ(i++, MetaAdapterFactory.getProperty(0xcf681fc9c7984f89L, 0xaf38ba3c0ac342d9L, 0x692d8403c84c5eb9L, 0x692d8403c84cb291L, "text"), "pack_header"));
    pvqMethods.put("5619175737692952794", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "struct "));
    pvqMethods.put("5619175737692848595", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "func"));
    pvqMethods.put("5619175737692929290", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "}"));
    pvqMethods.put("5619175737692848690", new PVQ(i++, MetaAdapterFactory.getProperty(0xcf681fc9c7984f89L, 0xaf38ba3c0ac342d9L, 0x692d8403c84c5eb9L, 0x692d8403c84cb291L, "text"), "pack_end"));
    pvqMethods.put("5619175737692848698", new PVQ(i++, MetaAdapterFactory.getProperty(0xcf681fc9c7984f89L, 0xaf38ba3c0ac342d9L, 0x692d8403c84c5eb9L, 0x692d8403c84cb291L, "text"), "size_check"));
    pvqMethods.put("5619175737692848735", new PVQ(i++, MetaAdapterFactory.getProperty(0xcf681fc9c7984f89L, 0xaf38ba3c0ac342d9L, 0x692d8403c84c5eb9L, 0x692d8403c84cb291L, "text"), "asString()"));
    pvqMethods.put("3463732535972196602", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "protocol"));
    pvqMethods.put("5619175737671724144", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "protocol"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    PropertyValueQuery query = identity.forTemplateNode(pvqMethods);
    return (query != null ? query : super.getPropertyValueQuery(identity));
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetValue_0_0(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetValue_0_1(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetValue_0_2(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetValue_0_3(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetValue_0_4(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetValue_0_5(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetValue_0_6(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetValue_0_7(ctx);
        case 8:
          return QueriesGenerated.propertyMacro_GetValue_0_8(ctx);
        case 9:
          return QueriesGenerated.propertyMacro_GetValue_0_9(ctx);
        case 10:
          return QueriesGenerated.propertyMacro_GetValue_0_10(ctx);
        case 11:
          return QueriesGenerated.propertyMacro_GetValue_0_11(ctx);
        case 12:
          return QueriesGenerated.propertyMacro_GetValue_0_12(ctx);
        case 13:
          return QueriesGenerated.propertyMacro_GetValue_0_13(ctx);
        case 14:
          return QueriesGenerated.propertyMacro_GetValue_0_14(ctx);
        case 15:
          return QueriesGenerated.propertyMacro_GetValue_0_15(ctx);
        case 16:
          return QueriesGenerated.propertyMacro_GetValue_0_16(ctx);
        case 17:
          return QueriesGenerated.propertyMacro_GetValue_0_17(ctx);
        case 18:
          return QueriesGenerated.propertyMacro_GetValue_0_18(ctx);
        case 19:
          return QueriesGenerated.propertyMacro_GetValue_0_19(ctx);
        case 20:
          return QueriesGenerated.propertyMacro_GetValue_0_20(ctx);
        case 21:
          return QueriesGenerated.propertyMacro_GetValue_0_21(ctx);
        case 22:
          return QueriesGenerated.propertyMacro_GetValue_0_22(ctx);
        case 23:
          return QueriesGenerated.propertyMacro_GetValue_0_23(ctx);
        case 24:
          return QueriesGenerated.propertyMacro_GetValue_0_24(ctx);
        case 25:
          return QueriesGenerated.propertyMacro_GetValue_0_25(ctx);
        case 26:
          return QueriesGenerated.propertyMacro_GetValue_0_26(ctx);
        case 27:
          return QueriesGenerated.propertyMacro_GetValue_0_27(ctx);
        case 28:
          return QueriesGenerated.propertyMacro_GetValue_0_28(ctx);
        case 29:
          return QueriesGenerated.propertyMacro_GetValue_0_29(ctx);
        case 30:
          return QueriesGenerated.propertyMacro_GetValue_1_0(ctx);
        case 31:
          return QueriesGenerated.propertyMacro_GetValue_2_0(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private static boolean isNotEmptyString(String str) {
    return str != null && str.length() > 0;
  }

  private static final class PROPS {
    /*package*/ static final SProperty genType$AtJI = MetaAdapterFactory.getProperty(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3cf6L, 0x4dfb528fce6bb464L, "genType");
    /*package*/ static final SProperty value$wDYR = MetaAdapterFactory.getProperty(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e24169c4L, 0x726a4e86e24169c5L, "value");
    /*package*/ static final SProperty value$$aYn = MetaAdapterFactory.getProperty(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a09L, 0x726a4e86e2416a20L, "value");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty value$wjFT = MetaAdapterFactory.getProperty(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e24169a5L, 0x726a4e86e24169a8L, "value");
    /*package*/ static final SProperty value$fPEt = MetaAdapterFactory.getProperty(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3d17L, 0x113e6c9588d675c6L, "value");
    /*package*/ static final SProperty value$fPcU = MetaAdapterFactory.getProperty(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3d18L, 0x113e6c9588d675c4L, "value");
    /*package*/ static final SProperty field$Acvf = MetaAdapterFactory.getProperty(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x136a49a7a3b2413fL, 0x136a49a7a448d2f0L, "field");
    /*package*/ static final SProperty length$wbxg = MetaAdapterFactory.getProperty(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416997L, 0x726a4e86e241699cL, "length");
    /*package*/ static final SProperty default$w7ZO = MetaAdapterFactory.getProperty(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a34L, 0x54785f5b32fc627eL, "default");
    /*package*/ static final SProperty counterOf$_QEd = MetaAdapterFactory.getProperty(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a34L, 0x394e4455c022c1baL, "counterOf");
    /*package*/ static final SProperty pos$ZoEI = MetaAdapterFactory.getProperty(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x61a1940705f3e4dfL, 0x61a1940705f3e4e2L, "pos");
    /*package*/ static final SProperty size$1BwP = MetaAdapterFactory.getProperty(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a26L, 0x584c9fdae0cb95d2L, "size");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept EBProtocol$zC = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3cf6L, "eb_lang.structure.EBProtocol");
    /*package*/ static final SConcept EBMessageMemberVar$_K = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x54785f5b332a751cL, "eb_lang.structure.EBMessageMemberVar");
    /*package*/ static final SConcept EBEnum$37 = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3d0dL, "eb_lang.structure.EBEnum");
    /*package*/ static final SConcept EBCharLiteral$iB = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3d18L, "eb_lang.structure.EBCharLiteral");
    /*package*/ static final SConcept EBNumberLiteral$i8 = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3d17L, "eb_lang.structure.EBNumberLiteral");
    /*package*/ static final SConcept EBMessagePresenceFieldMember$Z = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x61a1940705f3e4dfL, "eb_lang.structure.EBMessagePresenceFieldMember");
    /*package*/ static final SConcept EBMessageBlockMember$o = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a29L, "eb_lang.structure.EBMessageBlockMember");
    /*package*/ static final SConcept EBMessageEntryMember$fS = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a34L, "eb_lang.structure.EBMessageEntryMember");
    /*package*/ static final SConcept EBMessage$YV = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a26L, "eb_lang.structure.EBMessage");
    /*package*/ static final SConcept EBImportPrimitive$gU = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a06L, "eb_lang.structure.EBImportPrimitive");
    /*package*/ static final SConcept EBIntType$ej = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x78f986b06f13f864L, "eb_lang.structure.EBIntType");
    /*package*/ static final SConcept EBBitField$xS = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e241698fL, "eb_lang.structure.EBBitField");
    /*package*/ static final SConcept EBInclude$_h = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x5300c8f52845c9aaL, "eb_lang.structure.EBInclude");
    /*package*/ static final SConcept EBTypeStatement$o0 = MetaAdapterFactory.getConcept(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3cf3L, "eb_lang.structure.EBTypeStatement");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink base_member$uj3_ = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x136a49a7a3b2413fL, 0x136a49a7a448bb39L, "base_member");
    /*package*/ static final SReferenceLink base$F2Ny = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x136a49a7a3b2413fL, 0x136a49a7a3d4e29cL, "base");
    /*package*/ static final SContainmentLink content$vVwC = MetaAdapterFactory.getContainmentLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a26L, 0x7b5896debde675baL, "content");
    /*package*/ static final SReferenceLink derived$F3h$ = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x136a49a7a3b2413fL, 0x136a49a7a3d4e29eL, "derived");
    /*package*/ static final SReferenceLink type$eiFN = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a34L, 0x5737b24e0c67d176L, "type");
    /*package*/ static final SReferenceLink enum$iBH6 = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416997L, 0x5737b24e0c5eca32L, "enum");
    /*package*/ static final SReferenceLink default$Qsog = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416997L, 0x772be441ee43a938L, "default");
    /*package*/ static final SContainmentLink type$w4bT = MetaAdapterFactory.getContainmentLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e241698fL, 0x726a4e86e2416992L, "type");
    /*package*/ static final SContainmentLink values$w4DV = MetaAdapterFactory.getContainmentLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e241698fL, 0x726a4e86e2416994L, "values");
    /*package*/ static final SContainmentLink type$_ySl = MetaAdapterFactory.getContainmentLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3d0dL, 0x726a4e86e23f3d22L, "type");
    /*package*/ static final SContainmentLink value$_yQp = MetaAdapterFactory.getContainmentLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3d1dL, 0x726a4e86e23f3d20L, "value");
    /*package*/ static final SContainmentLink values$_zmn = MetaAdapterFactory.getContainmentLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3d0dL, 0x726a4e86e23f3d24L, "values");
    /*package*/ static final SContainmentLink type$zVeR = MetaAdapterFactory.getContainmentLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a06L, 0x726a4e86e2416a07L, "type");
    /*package*/ static final SReferenceLink type$kyUc = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a29L, 0x3e338995cb0feb1dL, "type");
    /*package*/ static final SReferenceLink counter$kzoe = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a29L, 0x3e338995cb0feb1fL, "counter");
    /*package*/ static final SReferenceLink presence_map$Zjwo = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x61a1940705f3e4dfL, 0x61a1940705f3e4e1L, "presence_map");
    /*package*/ static final SReferenceLink type$Zjhn = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x61a1940705f3e4dfL, 0x61a1940705f3e4e0L, "type");
    /*package*/ static final SReferenceLink base$LfNH = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e2416a26L, 0x1fd2ea8cbdac6546L, "base");
    /*package*/ static final SContainmentLink statements$_5KW = MetaAdapterFactory.getContainmentLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x726a4e86e23f3cf6L, 0x726a4e86e23f3cfcL, "statements");
    /*package*/ static final SReferenceLink protocol$v5qn = MetaAdapterFactory.getReferenceLink(0x59242254602f42f3L, 0xab3adc203eb4cc03L, 0x5300c8f52845c9aaL, 0x5300c8f52845c9abL, "protocol");
  }
}
