#this file is generated by exchbuf(https://github.com/ChrisYan6807/exchbuf), please do NOT edit it manually!!!
from .common import *
// Deutsche Börse -- market: edci_Cash, version: 14.1, subVersion: C0001, buildNumber: 141.420.0.ga-141004020-19

edci_CashAppVersionID = "14.1"
CurrencyType = fixed_length_string(3, '\0', False)
ISIN = fixed_length_string(12, '\0', False)
LocalMktDate = integer_type(LEIntField, 0, 99991231, 0xFFFFFFFF)
LocalMonthYearCod = integer_type(LEIntField, 0, 999912, 0xFFFFFFFF)
PriceType = float_decimal(8, 8, True, True, -9223372036854775807, 2**63-1, 0x8000000000000000)
Qty = float_decimal(8, 4, True, True, -9223372036854775807, 2**63-1, 0x8000000000000000)
UTCTimestamp = integer_type(LELongField, 0, 18446744073709551614, 0xFFFFFFFFFFFFFFFF)
AffectedClOrdID = integer_type(LELongField, 0, 18446744073709551614, 0xFFFFFFFFFFFFFFFF)
AffectedFIXClOrdID = fixed_length_string(20, '\0', False)
AffectedFIXOrigClOrdID = fixed_length_string(20, '\0', False)
AffectedOrderID = integer_type(LELongField, 0, 18446744073709551614, 0xFFFFFFFFFFFFFFFF)
AffectedOrigClOrdID = integer_type(LELongField, 0, 18446744073709551614, 0xFFFFFFFFFFFFFFFF)
class ApplID(int, Enum):
    OrderDropCopy = 12

class ApplSeqIndicator(int, Enum):
    No_Recovery_Required = 0
    Recovery_Required = 1

BodyLen = integer_type(LEIntField, 0, 4294967294, 0xFFFFFFFF)
BrokerInternalizationID = integer_type(LEIntField, 0, 4294967294, 0xFFFFFFFF)
ClOrdID = integer_type(LELongField, 0, 18446744073709551614, 0xFFFFFFFFFFFFFFFF)
class CrossMatchInstruction(int, Enum):
    Cancel_aggressive = 1
    Cancel_passive = 2
    Cancel_aggressive_and_passive = 3

class CrossedIndicator(int, Enum):
    No_crossing = 0
    Cross_rejected = 1

CumQty = float_decimal(8, 4, True, True, -9223372036854775807, 2**63-1, 0x8000000000000000)
CustOrderHandlingInst = fixed_length_string(1, '\0', False)
CxlQty = float_decimal(8, 4, True, True, -9223372036854775807, 2**63-1, 0x8000000000000000)
DefaultCstmApplVerID = fixed_length_string(30, '\0', False)
DefaultCstmApplVerSubID = fixed_length_string(5, '\0', False)
DisplayQty = float_decimal(8, 4, True, True, -9223372036854775807, 2**63-1, 0x8000000000000000)
ExecID = integer_type(LELongField, 0, 18446744073709551614, 0xFFFFFFFFFFFFFFFF)
class ExecInst(int, Enum):
    H = 1
    Q = 2
    H_6 = 5
    Q_6 = 6

class ExecType(bytes, Enum):
    New = b'0'
    Canceled = b'4'
    Replaced = b'5'
    Pending_Cancel_e = b'6'
    Suspended = b'9'
    Restated = b'D'
    Triggered = b'L'
    Trade = b'F'
    Pending_New = b'A'
    Pending_Replace = b'E'

ExecutingTrader = integer_type(LELongField, 1, 18446744073709551614, 0xFFFFFFFFFFFFFFFF)
class ExecutingTraderQualifier(int, Enum):
    Algo = 22
    Human = 24

ExpireDate = integer_type(LEIntField, 0, 99991231, 0xFFFFFFFF)
FIXClOrdID = fixed_length_string(20, '\0', False)
FIXOrigClOrdID = fixed_length_string(20, '\0', False)
FillExecID = integer_type(LESignedIntField, -2147483647, 2147483647, 0x80000000)
class FillLiquidityInd(int, Enum):
    Added_Liquidity = 1
    Removed_Liquidity = 2
    Auction = 4
    Triggered_Stop_Order = 5
    Triggered_OCO_Order = 6
    Triggered_Market_Order = 7
    Added_Liquidity_Midpoint = 100
    Removed_Liquidity_Midpoint = 101

FillMatchID = integer_type(LEIntField, 0, 4294967294, 0xFFFFFFFF)
FillPx = float_decimal(8, 8, True, True, -9223372036854775807, 2**63-1, 0x8000000000000000)
FillQty = float_decimal(8, 4, True, True, -9223372036854775807, 2**63-1, 0x8000000000000000)
FreeText1 = fixed_length_string(12, '\0', False)
FreeText2 = fixed_length_string(12, '\0', False)
FreeText4 = fixed_length_string(16, '\0', False)
HeartBtInt = integer_type(LEIntField, 0, 4294967294, 0xFFFFFFFF)
class LastFragment(int, Enum):
    Not_Last_Message = 0
    Last_Message = 1

LeavesQty = float_decimal(8, 4, True, True, -9223372036854775807, 2**63-1, 0x8000000000000000)
class MarketID(int, Enum):
    XETR = 3
    XVIE = 4
    XMAL = 6
    XBUL = 7
    XBUD = 8
    XLJU = 9
    XPRA = 10
    XZAG = 11
    XFRA = 13
    XDUS = 14
    XHAM = 15
    XHAN = 16
    XMUN = 17

MarketSegmentID = integer_type(LESignedIntField, -2147483647, 2147483647, 0x80000000)
MatchInstCrossID = integer_type(LEIntField, 0, 4294967294, 0xFFFFFFFF)
class MatchType(int, Enum):
    Auto_match_incoming = 4
    Cross_Auction = 5
    Call_Auction = 7
    Auto_match_resting = 11
    Auto_match_at_mid_point = 12
    Continuous_Auction = 14
    Retail = 15

class MidPointType(int, Enum):
    MidPoint = 1
    MidPointSweep = 2

MinQty = float_decimal(8, 4, True, True, -9223372036854775807, 2**63-1, 0x8000000000000000)
MsgSeqNum = integer_type(LEIntField, 0, 4294967294, 0xFFFFFFFF)
MsgType = fixed_length_string(3, '\0', False)
NoAffectedOrders = integer_type(LEShortField, 0, 500, 0xFFFF)
NoFills = integer_type(ByteField, 0, 100, 0xFF)
NoPartitions = integer_type(ByteField, 0, 100, 0xFF)
NoSessions = integer_type(LEShortField, 1, 1000, 0xFFFF)
class OrdStatus(bytes, Enum):
    New = b'0'
    Partially_filled = b'1'
    Filled = b'2'
    Canceled = b'4'
    Pending_Cancel = b'6'
    Suspended = b'9'
    Pending_New = b'A'
    Pending_Replace = b'E'

class OrdType(int, Enum):
    Market = 1
    Limit = 2
    Stop = 3
    Stop_Limit = 4

OrderID = integer_type(LELongField, 0, 18446744073709551614, 0xFFFFFFFFFFFFFFFF)
OrderIDSfx = integer_type(LEIntField, 0, 4294967294, 0xFFFFFFFF)
class OrderOrigination(int, Enum):
    Direct_access_customer = 5
    Sponsored_access_customer = 105

OrderQty = float_decimal(8, 4, True, True, -9223372036854775807, 2**63-1, 0x8000000000000000)
OrigClOrdID = integer_type(LELongField, 0, 18446744073709551614, 0xFFFFFFFFFFFFFFFF)
Pad2 = fixed_length_string(2, '\0', False)
Pad3 = fixed_length_string(3, '\0', False)
Pad4 = fixed_length_string(4, '\0', False)
Pad4_1 = fixed_length_string(4, '\0', False)
Pad4_2 = fixed_length_string(4, '\0', False)
Pad4_3 = fixed_length_string(4, '\0', False)
Pad5 = fixed_length_string(5, '\0', False)
Pad6 = fixed_length_string(6, '\0', False)
Pad7 = fixed_length_string(7, '\0', False)
PartitionID = integer_type(LEShortField, 0, 65534, 0xFFFF)
PartyExecutingFirm = fixed_length_string(5, '\0', False)
PartyIDClientID = integer_type(LELongField, 1, 18446744073709551614, 0xFFFFFFFFFFFFFFFF)
PartyIDExecutingTrader = integer_type(LEIntField, 0, 4294967294, 0xFFFFFFFF)
PartyIDExecutingUnit = integer_type(LEIntField, 0, 4294967294, 0xFFFFFFFF)
PartyIDSessionID = integer_type(LEIntField, 0, 4294967294, 0xFFFFFFFF)
PartyIDSponsoredAccessUnit = integer_type(LEIntField, 0, 4294967294, 0xFFFFFFFF)
PartyIdInvestmentDecisionMaker = integer_type(LELongField, 1, 18446744073709551614, 0xFFFFFFFFFFFFFFFF)
class PartyIdInvestmentDecisionMakerQualifier(int, Enum):
    Algo = 22
    Human = 24

PartySponsoredAccessUnit = fixed_length_string(30, '\0', False)
Password = fixed_length_string(32, '\0', False)
PegOffsetValueAbs = float_decimal(8, 8, True, True, -9223372036854775807, 2**63-1, 0x8000000000000000)
PegOffsetValuePct = float_decimal(8, 4, True, True, -9223372036854775807, 2**63-1, 0x8000000000000000)
Price = float_decimal(8, 8, True, True, -9223372036854775807, 2**63-1, 0x8000000000000000)
RequestTime = integer_type(LELongField, 0, 18446744073709551614, 0xFFFFFFFFFFFFFFFF)
SecurityID = integer_type(LESignedLongField, -9223372036854775807, 9223372036854775807, 0x8000000000000000)
class SelfMatchPreventionInstruction(int, Enum):
    Cross_rejected_BU = 100
    Cross_rejected_Market = 101

SendingTime = integer_type(LELongField, 0, 18446744073709551614, 0xFFFFFFFFFFFFFFFF)
SessionInstanceID = integer_type(LEIntField, 0, 4294967294, 0xFFFFFFFF)
class SessionMode(int, Enum):
    ETI_HF = 1
    ETI_LF = 2
    GUI = 3
    FIX_LF = 4

class SessionRejectReason(int, Enum):
    Required_Tag_Missing = 1
    Value_is_incorrect = 5
    Decryption_problem = 7
    Invalid_MsgID = 11
    Incorrect_NumInGroup_count = 16
    Other = 99
    Exposure_Limit_Exceeded = 101
    Service_Not_Available = 103
    Outbound_conversion_error = 105
    Heartbeat_Violation = 152
    Internal_technical_error = 200
    Validation_Error = 210
    Session_Login_Limit_Reached = 217
    Outstanding_Logins_Bu_Limit_Reached = 226
    Outstanding_Logins_Session_Limit_Reached = 227
    Password_Timestamp_Not_In_Grace_Period = 228

class SessionStatus(int, Enum):
    Active = 0
    Logout = 4

class Side(int, Enum):
    Buy = 1
    Sell = 2

StopPx = float_decimal(8, 8, True, True, -9223372036854775807, 2**63-1, 0x8000000000000000)
class TimeInForce(int, Enum):
    Day = 0
    GTC = 1
    IOC = 3
    FOK = 4
    GTD = 6

class TradSesEvent(int, Enum):
    End_of_Restatement = 103
    End_of_Day_Service = 104
    End_of_Order_book_synch = 107
    Start_of_Order_book_synch = 108
    Order_book_reset = 109

class TradSesMode(int, Enum):
    Testing = 1
    Simulated = 2
    Production = 3
    Acceptance = 4
    Disaster_Recovery = 5

class TradeAtCloseOptIn(int, Enum):
    No = 0
    Yes = 1

TradeDate = integer_type(LEIntField, 0, 99991231, 0xFFFFFFFF)
class TradingCapacity(int, Enum):
    Customer = 1
    Broker_dealer = 3
    Principal = 5
    Market_Maker = 6
    Riskless_Principal = 9
    Retail_Customer = 10
    Retail_Market_Maker = 11

class TradingSessionSubID(int, Enum):
    Opening_auction = 2
    Closing_auction = 4
    Intraday_Auction = 6
    Any_Auction = 8
    Special_Auction = 105
    Main_Trading_Hours = 106
    AVD_Opening_Auction = 107
    AVD_Intraday_Auction = 108
    AVD_Closing_Auction = 109

class Triggered(int, Enum):
    Not_triggered = 0
    Triggered_Stop = 1
    Triggered_OCO = 2

VarText = fixed_length_string(2000, '\0', False)
VarTextLen = integer_type(LEShortField, 0, 2000, 0xFFFF)
class TemplateID(int, Enum):
    DeleteOrderBroadcast = 10902
    ForcedLogoutNotification = 10012
    Heartbeat = 10011
    HeartbeatNotification = 10023
    LogonRequest = 10000
    LogonResponse = 10001
    LogoutRequest = 10002
    LogoutResponse = 10003
    OrderExecReportBroadcast = 10901
    PartitionListNotification = 10037
    Reject = 10010
    SessionListNotification = 10036
    SessionStatusBroadcast = 10903
    TrailingStopUpdateNotification = 10904

class AffectedOrdGrpComp(Packet):
    name = 'AffectedOrdGrpComp'
    fields_desc = [
    AffectedOrderID("affectedOrderID", 0xFFFFFFFFFFFFFFFF),
    AffectedClOrdID("affectedClOrdID", 0xFFFFFFFFFFFFFFFF),
    AffectedOrigClOrdID("affectedOrigClOrdID", 0xFFFFFFFFFFFFFFFF),
    SecurityID("securityID", 0x8000000000000000),
    OrderIDSfx("orderIDSfx", 0xFFFFFFFF),
    PartyIDSessionID("partyIDSessionID", 0xFFFFFFFF),
    PartyIDExecutingTrader("partyIDExecutingTrader", 0xFFFFFFFF),
    CharEnumField("ordStatus", OrdStatus.Pending_Replace, OrdStatus),
    CharEnumField("execType", ExecType.Pending_Replace, ExecType),
    AffectedFIXClOrdID("affectedFIXClOrdID", ""),
    AffectedFIXOrigClOrdID("affectedFIXOrigClOrdID", ""),
    Pad2("pad2", ""),
    ]

class FillsGrpComp(Packet):
    name = 'FillsGrpComp'
    fields_desc = [
    FillPx("fillPx", 0x8000000000000000),
    FillQty("fillQty", 0x8000000000000000),
    FillMatchID("fillMatchID", 0xFFFFFFFF),
    FillExecID("fillExecID", 0x80000000),
    ByteEnumField("fillLiquidityInd", FillLiquidityInd.Removed_Liquidity_Midpoint, FillLiquidityInd),
    Pad7("pad7", ""),
    ]

class MessageHeaderInComp(Packet):
    name = 'MessageHeaderInComp'
    fields_desc = [
    BodyLen("bodyLen", 0xFFFFFFFF),
    LEShortEnumField("templateID", TemplateID.TrailingStopUpdateNotification, TemplateID),
    Pad2("pad2", ""),
    ]

class MessageHeaderOutComp(Packet):
    name = 'MessageHeaderOutComp'
    fields_desc = [
    BodyLen("bodyLen", 0xFFFFFFFF),
    LEShortEnumField("templateID", TemplateID.TrailingStopUpdateNotification, TemplateID),
    Pad2("pad2", ""),
    ]

class NotifHeaderComp(Packet):
    name = 'NotifHeaderComp'
    fields_desc = [
    SendingTime("sendingTime", 0xFFFFFFFFFFFFFFFF),
    ]

class PartitionGrpComp(Packet):
    name = 'PartitionGrpComp'
    fields_desc = [
    PartitionID("partitionID", 0xFFFF),
    Pad6("pad6", ""),
    ]

class RBCHeaderComp(Packet):
    name = 'RBCHeaderComp'
    fields_desc = [
    SendingTime("sendingTime", 0xFFFFFFFFFFFFFFFF),
    PartyIDExecutingUnit("partyIDExecutingUnit", 0xFFFFFFFF),
    PartitionID("partitionID", 0xFFFF),
    ByteEnumField("applID", ApplID.OrderDropCopy, ApplID),
    ByteEnumField("lastFragment", LastFragment.Last_Message, LastFragment),
    ]

class RequestHeaderComp(Packet):
    name = 'RequestHeaderComp'
    fields_desc = [
    MsgSeqNum("msgSeqNum", 0xFFFFFFFF),
    Pad4("pad4", ""),
    ]

class ResponseHeaderComp(Packet):
    name = 'ResponseHeaderComp'
    fields_desc = [
    RequestTime("requestTime", 0xFFFFFFFFFFFFFFFF),
    SendingTime("sendingTime", 0xFFFFFFFFFFFFFFFF),
    MsgSeqNum("msgSeqNum", 0xFFFFFFFF),
    ByteEnumField("lastFragment", LastFragment.Last_Message, LastFragment),
    Pad3("pad3", ""),
    ]

class SessionsGrpComp(Packet):
    name = 'SessionsGrpComp'
    fields_desc = [
    PartyIDSessionID("partyIDSessionID", 0xFFFFFFFF),
    PartyIDExecutingUnit("partyIDExecutingUnit", 0xFFFFFFFF),
    PartyIDSponsoredAccessUnit("partyIDSponsoredAccessUnit", 0xFFFFFFFF),
    ByteEnumField("sessionMode", SessionMode.FIX_LF, SessionMode),
    PartyExecutingFirm("partyExecutingFirm", ""),
    PartySponsoredAccessUnit("partySponsoredAccessUnit", ""),
    ]

class DeleteOrderBroadcast(Packet):
    name = 'DeleteOrderBroadcast'
    fields_desc = [
    PacketField("messageHeaderOut", "", MessageHeaderOutComp),
    PacketField("rBCHeader", "", RBCHeaderComp),
    ExecID("execID", 0xFFFFFFFFFFFFFFFF),
    MarketSegmentID("marketSegmentID", 0x80000000),
    FieldLenField("noAffectedOrders", 0, fmt="<H", count_of="affectedOrdGrp"),
    Pad2("pad2", ""),
        PacketListField("affectedOrdGrp", None, AffectedOrdGrpComp, count_from=lambda pkt:pkt.noAffectedOrders
    ]

class ForcedLogoutNotification(Packet):
    name = 'ForcedLogoutNotification'
    fields_desc = [
    PacketField("messageHeaderOut", "", MessageHeaderOutComp),
    PacketField("notifHeader", "", NotifHeaderComp),
    FieldLenField("varTextLen", 0, fmt="<H", count_of="varText"),
        PacketListField("varText", None, VarText, count_from=lambda pkt:pkt.varTextLen
    ]

class Heartbeat(Packet):
    name = 'Heartbeat'
    fields_desc = [
    PacketField("messageHeaderIn", "", MessageHeaderInComp),
    ]

class HeartbeatNotification(Packet):
    name = 'HeartbeatNotification'
    fields_desc = [
    PacketField("messageHeaderOut", "", MessageHeaderOutComp),
    PacketField("notifHeader", "", NotifHeaderComp),
    ]

class LogonRequest(Packet):
    name = 'LogonRequest'
    fields_desc = [
    PacketField("messageHeaderIn", "", MessageHeaderInComp),
    PacketField("requestHeader", "", RequestHeaderComp),
    HeartBtInt("heartBtInt", 0xFFFFFFFF),
    PartyIDSessionID("partyIDSessionID", 0xFFFFFFFF),
    DefaultCstmApplVerID("defaultCstmApplVerID", ""),
    Password("password", ""),
    Pad2("pad2", ""),
    ]

class LogonResponse(Packet):
    name = 'LogonResponse'
    fields_desc = [
    PacketField("messageHeaderOut", "", MessageHeaderOutComp),
    PacketField("responseHeader", "", ResponseHeaderComp),
    HeartBtInt("heartBtInt", 0xFFFFFFFF),
    SessionInstanceID("sessionInstanceID", 0xFFFFFFFF),
    LEShortEnumField("marketID", MarketID.XMUN, MarketID),
    ByteEnumField("tradSesMode", TradSesMode.Disaster_Recovery, TradSesMode),
    DefaultCstmApplVerID("defaultCstmApplVerID", ""),
    DefaultCstmApplVerSubID("defaultCstmApplVerSubID", ""),
    Pad2("pad2", ""),
    ]

class LogoutRequest(Packet):
    name = 'LogoutRequest'
    fields_desc = [
    PacketField("messageHeaderIn", "", MessageHeaderInComp),
    PacketField("requestHeader", "", RequestHeaderComp),
    ]

class LogoutResponse(Packet):
    name = 'LogoutResponse'
    fields_desc = [
    PacketField("messageHeaderOut", "", MessageHeaderOutComp),
    PacketField("responseHeader", "", ResponseHeaderComp),
    ]

class OrderExecReportBroadcast(Packet):
    name = 'OrderExecReportBroadcast'
    fields_desc = [
    PacketField("messageHeaderOut", "", MessageHeaderOutComp),
    PacketField("rBCHeader", "", RBCHeaderComp),
    OrderID("orderID", 0xFFFFFFFFFFFFFFFF),
    ClOrdID("clOrdID", 0xFFFFFFFFFFFFFFFF),
    OrigClOrdID("origClOrdID", 0xFFFFFFFFFFFFFFFF),
    SecurityID("securityID", 0x8000000000000000),
    ExecID("execID", 0xFFFFFFFFFFFFFFFF),
    Price("price", 0x8000000000000000),
    StopPx("stopPx", 0x8000000000000000),
    LeavesQty("leavesQty", 0x8000000000000000),
    CumQty("cumQty", 0x8000000000000000),
    CxlQty("cxlQty", 0x8000000000000000),
    OrderQty("orderQty", 0x8000000000000000),
    MinQty("minQty", 0x8000000000000000),
    DisplayQty("displayQty", 0x8000000000000000),
    PegOffsetValueAbs("pegOffsetValueAbs", 0x8000000000000000),
    PegOffsetValuePct("pegOffsetValuePct", 0x8000000000000000),
    PartyIDClientID("partyIDClientID", 0xFFFFFFFFFFFFFFFF),
    PartyIdInvestmentDecisionMaker("partyIdInvestmentDecisionMaker", 0xFFFFFFFFFFFFFFFF),
    ExecutingTrader("executingTrader", 0xFFFFFFFFFFFFFFFF),
    BrokerInternalizationID("brokerInternalizationID", 0xFFFFFFFF),
    MarketSegmentID("marketSegmentID", 0x80000000),
    OrderIDSfx("orderIDSfx", 0xFFFFFFFF),
    MatchInstCrossID("matchInstCrossID", 0xFFFFFFFF),
    ExpireDate("expireDate", 0xFFFFFFFF),
    PartyIDSessionID("partyIDSessionID", 0xFFFFFFFF),
    PartyIDExecutingTrader("partyIDExecutingTrader", 0xFFFFFFFF),
    CharEnumField("ordStatus", OrdStatus.Pending_Replace, OrdStatus),
    CharEnumField("execType", ExecType.Pending_Replace, ExecType),
    ByteEnumField("side", Side.Sell, Side),
    ByteEnumField("ordType", OrdType.Stop_Limit, OrdType),
    ByteEnumField("matchType", MatchType.Retail, MatchType),
    ByteEnumField("tradingCapacity", TradingCapacity.Retail_Market_Maker, TradingCapacity),
    ByteEnumField("timeInForce", TimeInForce.GTD, TimeInForce),
    ByteEnumField("execInst", ExecInst.Q_6, ExecInst),
    ByteEnumField("triggered", Triggered.Triggered_OCO, Triggered),
    ByteEnumField("tradingSessionSubID", TradingSessionSubID.AVD_Closing_Auction, TradingSessionSubID),
    ByteEnumField("applSeqIndicator", ApplSeqIndicator.Recovery_Required, ApplSeqIndicator),
    ByteEnumField("selfMatchPreventionInstruction", SelfMatchPreventionInstruction.Cross_rejected_Market, SelfMatchPreventionInstruction),
    ByteEnumField("crossMatchInstruction", CrossMatchInstruction.Cancel_aggressive_and_passive, CrossMatchInstruction),
    ByteEnumField("partyIdInvestmentDecisionMakerQualifier", PartyIdInvestmentDecisionMakerQualifier.Human, PartyIdInvestmentDecisionMakerQualifier),
    ByteEnumField("executingTraderQualifier", ExecutingTraderQualifier.Human, ExecutingTraderQualifier),
    FieldLenField("noFills", 0, fmt="<B", count_of="fillsGrp"),
    ByteEnumField("crossedIndicator", CrossedIndicator.Cross_rejected, CrossedIndicator),
    CustOrderHandlingInst("custOrderHandlingInst", ""),
    ByteEnumField("midPointType", MidPointType.MidPointSweep, MidPointType),
    ByteEnumField("tradeAtCloseOptIn", TradeAtCloseOptIn.Yes, TradeAtCloseOptIn),
    ByteEnumField("orderOrigination", OrderOrigination.Sponsored_access_customer, OrderOrigination),
    FreeText1("freeText1", ""),
    FreeText2("freeText2", ""),
    FreeText4("freeText4", ""),
    FIXClOrdID("fIXClOrdID", ""),
    FIXOrigClOrdID("fIXOrigClOrdID", ""),
    Pad7("pad7", ""),
        PacketListField("fillsGrp", None, FillsGrpComp, count_from=lambda pkt:pkt.noFills
    ]

class PartitionListNotification(Packet):
    name = 'PartitionListNotification'
    fields_desc = [
    PacketField("messageHeaderOut", "", MessageHeaderOutComp),
    PacketField("notifHeader", "", NotifHeaderComp),
    FieldLenField("noPartitions", 0, fmt="<B", count_of="partitionGrp"),
    Pad7("pad7", ""),
        PacketListField("partitionGrp", None, PartitionGrpComp, count_from=lambda pkt:pkt.noPartitions
    ]

class Reject(Packet):
    name = 'Reject'
    fields_desc = [
    PacketField("messageHeaderOut", "", MessageHeaderOutComp),
    PacketField("responseHeader", "", ResponseHeaderComp),
    LEIntEnumField("sessionRejectReason", SessionRejectReason.Password_Timestamp_Not_In_Grace_Period, SessionRejectReason),
    FieldLenField("varTextLen", 0, fmt="<H", count_of="varText"),
    ByteEnumField("sessionStatus", SessionStatus.Logout, SessionStatus),
        PacketListField("varText", None, VarText, count_from=lambda pkt:pkt.varTextLen
    ]

class SessionListNotification(Packet):
    name = 'SessionListNotification'
    fields_desc = [
    PacketField("messageHeaderOut", "", MessageHeaderOutComp),
    PacketField("notifHeader", "", NotifHeaderComp),
    FieldLenField("noSessions", 0, fmt="<H", count_of="sessionsGrp"),
    Pad6("pad6", ""),
        PacketListField("sessionsGrp", None, SessionsGrpComp, count_from=lambda pkt:pkt.noSessions
    ]

class SessionStatusBroadcast(Packet):
    name = 'SessionStatusBroadcast'
    fields_desc = [
    PacketField("messageHeaderOut", "", MessageHeaderOutComp),
    PacketField("rBCHeader", "", RBCHeaderComp),
    TradeDate("tradeDate", 0xFFFFFFFF),
    MarketSegmentID("marketSegmentID", 0x80000000),
    ByteEnumField("tradSesEvent", TradSesEvent.Order_book_reset, TradSesEvent),
    Pad7("pad7", ""),
    ]

class TrailingStopUpdateNotification(Packet):
    name = 'TrailingStopUpdateNotification'
    fields_desc = [
    PacketField("messageHeaderOut", "", MessageHeaderOutComp),
    PacketField("rBCHeader", "", RBCHeaderComp),
    OrderID("orderID", 0xFFFFFFFFFFFFFFFF),
    ClOrdID("clOrdID", 0xFFFFFFFFFFFFFFFF),
    OrigClOrdID("origClOrdID", 0xFFFFFFFFFFFFFFFF),
    SecurityID("securityID", 0x8000000000000000),
    ExecID("execID", 0xFFFFFFFFFFFFFFFF),
    StopPx("stopPx", 0x8000000000000000),
    OrderQty("orderQty", 0x8000000000000000),
    OrderIDSfx("orderIDSfx", 0xFFFFFFFF),
    MarketSegmentID("marketSegmentID", 0x80000000),
    ByteEnumField("side", Side.Sell, Side),
    FIXClOrdID("fIXClOrdID", ""),
    FIXOrigClOrdID("fIXOrigClOrdID", ""),
    Pad7("pad7", ""),
    ]



