#pragma once
//this file is generated by exchbuf(https://github.com/ChrisYan6807/exchbuf), please do NOT edit it manually!!!
#include "eb_common.hpp"

//Deutsche Börse -- market: edci_Cash, version: 14.1, subVersion: C0001, buildNumber: 141.420.0.ga-141004020-19

inline std::string edci_CashAppVersionID = "14.1";
namespace DBEDCI_141_Cash {
using namespace EB::common;

using CurrencyType = FixedLengthString<3, '\0', false>;
using ISIN = FixedLengthString<12, '\0', false>;
using LocalMktDate = LittleEndian<uint32_t, 0, 99991231, 0xFFFFFFFF>;
using LocalMonthYearCod = LittleEndian<uint32_t, 0, 999912, 0xFFFFFFFF>;
using PriceType = LittleEndian<int64_t, -9223372036854775807LL, std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min(), 8>;
using Qty = LittleEndian<int64_t, -9223372036854775807LL, std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min(), 4>;
using UTCTimestamp = LittleEndian<uint64_t, 0UL, 18446744073709551614UL, 0xFFFFFFFFFFFFFFFFUL>;
using AffectedClOrdID = LittleEndian<uint64_t, 0UL, 18446744073709551614UL, 0xFFFFFFFFFFFFFFFFUL>;
using AffectedFIXClOrdID = FixedLengthString<20, '\0', false>;
using AffectedFIXOrigClOrdID = FixedLengthString<20, '\0', false>;
using AffectedOrderID = LittleEndian<uint64_t, 0UL, 18446744073709551614UL, 0xFFFFFFFFFFFFFFFFUL>;
using AffectedOrigClOrdID = LittleEndian<uint64_t, 0UL, 18446744073709551614UL, 0xFFFFFFFFFFFFFFFFUL>;
struct ApplID {
    using value_type = uint8_t;
    enum Enum : value_type {
        OrderDropCopy = 12,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "ApplID";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(12), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(12), });
    constexpr ApplID():value_{max_value} {}
    constexpr explicit ApplID(uint8_t v):value_{v} {}
    constexpr ApplID(Enum v):value_{v} {}
    constexpr bool operator==(const ApplID& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const ApplID& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr ApplID& operator=(Enum v) {value_ == v;return *this;}
    constexpr ApplID& operator=(const ApplID& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::OrderDropCopy: return "OrderDropCopy";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const ApplID& v){
    os << v.view();
    return os;
}
struct ApplSeqIndicator {
    using value_type = uint8_t;
    enum Enum : value_type {
        No_Recovery_Required = 0,
        Recovery_Required = 1,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "ApplSeqIndicator";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(0), static_cast<uint8_t>(1), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(0), static_cast<uint8_t>(1), });
    constexpr ApplSeqIndicator():value_{max_value} {}
    constexpr explicit ApplSeqIndicator(uint8_t v):value_{v} {}
    constexpr ApplSeqIndicator(Enum v):value_{v} {}
    constexpr bool operator==(const ApplSeqIndicator& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const ApplSeqIndicator& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr ApplSeqIndicator& operator=(Enum v) {value_ == v;return *this;}
    constexpr ApplSeqIndicator& operator=(const ApplSeqIndicator& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::No_Recovery_Required: return "No_Recovery_Required";
            case Enum::Recovery_Required: return "Recovery_Required";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const ApplSeqIndicator& v){
    os << v.view();
    return os;
}
using BodyLen = LittleEndian<uint32_t, 0, 4294967294, 0xFFFFFFFF>;
using BrokerInternalizationID = LittleEndian<uint32_t, 0, 4294967294, 0xFFFFFFFF>;
using ClOrdID = LittleEndian<uint64_t, 0UL, 18446744073709551614UL, 0xFFFFFFFFFFFFFFFFUL>;
struct CrossMatchInstruction {
    using value_type = uint8_t;
    enum Enum : value_type {
        Cancel_aggressive = 1,
        Cancel_passive = 2,
        Cancel_aggressive_and_passive = 3,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "CrossMatchInstruction";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(3), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(3), });
    constexpr CrossMatchInstruction():value_{max_value} {}
    constexpr explicit CrossMatchInstruction(uint8_t v):value_{v} {}
    constexpr CrossMatchInstruction(Enum v):value_{v} {}
    constexpr bool operator==(const CrossMatchInstruction& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const CrossMatchInstruction& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr CrossMatchInstruction& operator=(Enum v) {value_ == v;return *this;}
    constexpr CrossMatchInstruction& operator=(const CrossMatchInstruction& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Cancel_aggressive: return "Cancel_aggressive";
            case Enum::Cancel_passive: return "Cancel_passive";
            case Enum::Cancel_aggressive_and_passive: return "Cancel_aggressive_and_passive";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const CrossMatchInstruction& v){
    os << v.view();
    return os;
}
struct CrossedIndicator {
    using value_type = uint8_t;
    enum Enum : value_type {
        No_crossing = 0,
        Cross_rejected = 1,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "CrossedIndicator";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(0), static_cast<uint8_t>(1), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(0), static_cast<uint8_t>(1), });
    constexpr CrossedIndicator():value_{max_value} {}
    constexpr explicit CrossedIndicator(uint8_t v):value_{v} {}
    constexpr CrossedIndicator(Enum v):value_{v} {}
    constexpr bool operator==(const CrossedIndicator& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const CrossedIndicator& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr CrossedIndicator& operator=(Enum v) {value_ == v;return *this;}
    constexpr CrossedIndicator& operator=(const CrossedIndicator& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::No_crossing: return "No_crossing";
            case Enum::Cross_rejected: return "Cross_rejected";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const CrossedIndicator& v){
    os << v.view();
    return os;
}
using CumQty = LittleEndian<int64_t, -9223372036854775807LL, std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min(), 4>;
using CustOrderHandlingInst = FixedLengthString<1, '\0', false>;
using CxlQty = LittleEndian<int64_t, -9223372036854775807LL, std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min(), 4>;
using DefaultCstmApplVerID = FixedLengthString<30, '\0', false>;
using DefaultCstmApplVerSubID = FixedLengthString<5, '\0', false>;
using DisplayQty = LittleEndian<int64_t, -9223372036854775807LL, std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min(), 4>;
using ExecID = LittleEndian<uint64_t, 0UL, 18446744073709551614UL, 0xFFFFFFFFFFFFFFFFUL>;
struct ExecInst {
    using value_type = uint8_t;
    enum Enum : value_type {
        H = 1,
        Q = 2,
        H_6 = 5,
        Q_6 = 6,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "ExecInst";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(5), static_cast<uint8_t>(6), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(5), static_cast<uint8_t>(6), });
    constexpr ExecInst():value_{max_value} {}
    constexpr explicit ExecInst(uint8_t v):value_{v} {}
    constexpr ExecInst(Enum v):value_{v} {}
    constexpr bool operator==(const ExecInst& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const ExecInst& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr ExecInst& operator=(Enum v) {value_ == v;return *this;}
    constexpr ExecInst& operator=(const ExecInst& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::H: return "H";
            case Enum::Q: return "Q";
            case Enum::H_6: return "H_6";
            case Enum::Q_6: return "Q_6";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const ExecInst& v){
    os << v.view();
    return os;
}
struct ExecType {
    using value_type = char;
    enum Enum : value_type {
        New = '0',
        Canceled = '4',
        Replaced = '5',
        Pending_Cancel_e = '6',
        Suspended = '9',
        Restated = 'D',
        Triggered = 'L',
        Trade = 'F',
        Pending_New = 'A',
        Pending_Replace = 'E',
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "ExecType";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<char>('0'), static_cast<char>('4'), static_cast<char>('5'), static_cast<char>('6'), static_cast<char>('9'), static_cast<char>('D'), static_cast<char>('L'), static_cast<char>('F'), static_cast<char>('A'), static_cast<char>('E'), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<char>('0'), static_cast<char>('4'), static_cast<char>('5'), static_cast<char>('6'), static_cast<char>('9'), static_cast<char>('D'), static_cast<char>('L'), static_cast<char>('F'), static_cast<char>('A'), static_cast<char>('E'), });
    constexpr ExecType():value_{max_value} {}
    constexpr explicit ExecType(char v):value_{v} {}
    constexpr ExecType(Enum v):value_{v} {}
    constexpr bool operator==(const ExecType& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const ExecType& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr char raw_value() const {return static_cast<char>(value_);}
    constexpr void raw_value(char v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr ExecType& operator=(Enum v) {value_ == v;return *this;}
    constexpr ExecType& operator=(const ExecType& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::New: return "New";
            case Enum::Canceled: return "Canceled";
            case Enum::Replaced: return "Replaced";
            case Enum::Pending_Cancel_e: return "Pending_Cancel_e";
            case Enum::Suspended: return "Suspended";
            case Enum::Restated: return "Restated";
            case Enum::Triggered: return "Triggered";
            case Enum::Trade: return "Trade";
            case Enum::Pending_New: return "Pending_New";
            case Enum::Pending_Replace: return "Pending_Replace";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const ExecType& v){
    os << v.view();
    return os;
}
using ExecutingTrader = LittleEndian<uint64_t, 1UL, 18446744073709551614UL, 0xFFFFFFFFFFFFFFFFUL>;
struct ExecutingTraderQualifier {
    using value_type = uint8_t;
    enum Enum : value_type {
        Algo = 22,
        Human = 24,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "ExecutingTraderQualifier";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(22), static_cast<uint8_t>(24), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(22), static_cast<uint8_t>(24), });
    constexpr ExecutingTraderQualifier():value_{max_value} {}
    constexpr explicit ExecutingTraderQualifier(uint8_t v):value_{v} {}
    constexpr ExecutingTraderQualifier(Enum v):value_{v} {}
    constexpr bool operator==(const ExecutingTraderQualifier& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const ExecutingTraderQualifier& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr ExecutingTraderQualifier& operator=(Enum v) {value_ == v;return *this;}
    constexpr ExecutingTraderQualifier& operator=(const ExecutingTraderQualifier& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Algo: return "Algo";
            case Enum::Human: return "Human";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const ExecutingTraderQualifier& v){
    os << v.view();
    return os;
}
using ExpireDate = LittleEndian<uint32_t, 0, 99991231, 0xFFFFFFFF>;
using FIXClOrdID = FixedLengthString<20, '\0', false>;
using FIXOrigClOrdID = FixedLengthString<20, '\0', false>;
using FillExecID = LittleEndian<int32_t, -2147483647, 2147483647, std::numeric_limits<int32_t>::min()>;
struct FillLiquidityInd {
    using value_type = uint8_t;
    enum Enum : value_type {
        Added_Liquidity = 1,
        Removed_Liquidity = 2,
        Auction = 4,
        Triggered_Stop_Order = 5,
        Triggered_OCO_Order = 6,
        Triggered_Market_Order = 7,
        Added_Liquidity_Midpoint = 100,
        Removed_Liquidity_Midpoint = 101,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "FillLiquidityInd";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(4), static_cast<uint8_t>(5), static_cast<uint8_t>(6), static_cast<uint8_t>(7), static_cast<uint8_t>(100), static_cast<uint8_t>(101), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(4), static_cast<uint8_t>(5), static_cast<uint8_t>(6), static_cast<uint8_t>(7), static_cast<uint8_t>(100), static_cast<uint8_t>(101), });
    constexpr FillLiquidityInd():value_{max_value} {}
    constexpr explicit FillLiquidityInd(uint8_t v):value_{v} {}
    constexpr FillLiquidityInd(Enum v):value_{v} {}
    constexpr bool operator==(const FillLiquidityInd& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const FillLiquidityInd& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr FillLiquidityInd& operator=(Enum v) {value_ == v;return *this;}
    constexpr FillLiquidityInd& operator=(const FillLiquidityInd& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Added_Liquidity: return "Added_Liquidity";
            case Enum::Removed_Liquidity: return "Removed_Liquidity";
            case Enum::Auction: return "Auction";
            case Enum::Triggered_Stop_Order: return "Triggered_Stop_Order";
            case Enum::Triggered_OCO_Order: return "Triggered_OCO_Order";
            case Enum::Triggered_Market_Order: return "Triggered_Market_Order";
            case Enum::Added_Liquidity_Midpoint: return "Added_Liquidity_Midpoint";
            case Enum::Removed_Liquidity_Midpoint: return "Removed_Liquidity_Midpoint";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const FillLiquidityInd& v){
    os << v.view();
    return os;
}
using FillMatchID = LittleEndian<uint32_t, 0, 4294967294, 0xFFFFFFFF>;
using FillPx = LittleEndian<int64_t, -9223372036854775807LL, std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min(), 8>;
using FillQty = LittleEndian<int64_t, -9223372036854775807LL, std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min(), 4>;
using FreeText1 = FixedLengthString<12, '\0', false>;
using FreeText2 = FixedLengthString<12, '\0', false>;
using FreeText4 = FixedLengthString<16, '\0', false>;
using HeartBtInt = LittleEndian<uint32_t, 0, 4294967294, 0xFFFFFFFF>;
struct LastFragment {
    using value_type = uint8_t;
    enum Enum : value_type {
        Not_Last_Message = 0,
        Last_Message = 1,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "LastFragment";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(0), static_cast<uint8_t>(1), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(0), static_cast<uint8_t>(1), });
    constexpr LastFragment():value_{max_value} {}
    constexpr explicit LastFragment(uint8_t v):value_{v} {}
    constexpr LastFragment(Enum v):value_{v} {}
    constexpr bool operator==(const LastFragment& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const LastFragment& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr LastFragment& operator=(Enum v) {value_ == v;return *this;}
    constexpr LastFragment& operator=(const LastFragment& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Not_Last_Message: return "Not_Last_Message";
            case Enum::Last_Message: return "Last_Message";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const LastFragment& v){
    os << v.view();
    return os;
}
using LeavesQty = LittleEndian<int64_t, -9223372036854775807LL, std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min(), 4>;
struct MarketID {
    using value_type = uint16_t;
    enum Enum : value_type {
        XETR = 3,
        XVIE = 4,
        XMAL = 6,
        XBUL = 7,
        XBUD = 8,
        XLJU = 9,
        XPRA = 10,
        XZAG = 11,
        XFRA = 13,
        XDUS = 14,
        XHAM = 15,
        XHAN = 16,
        XMUN = 17,
    };
    static constexpr size_t size = 2;
    static constexpr char* name() {return "MarketID";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint16_t>(3), static_cast<uint16_t>(4), static_cast<uint16_t>(6), static_cast<uint16_t>(7), static_cast<uint16_t>(8), static_cast<uint16_t>(9), static_cast<uint16_t>(10), static_cast<uint16_t>(11), static_cast<uint16_t>(13), static_cast<uint16_t>(14), static_cast<uint16_t>(15), static_cast<uint16_t>(16), static_cast<uint16_t>(17), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint16_t>(3), static_cast<uint16_t>(4), static_cast<uint16_t>(6), static_cast<uint16_t>(7), static_cast<uint16_t>(8), static_cast<uint16_t>(9), static_cast<uint16_t>(10), static_cast<uint16_t>(11), static_cast<uint16_t>(13), static_cast<uint16_t>(14), static_cast<uint16_t>(15), static_cast<uint16_t>(16), static_cast<uint16_t>(17), });
    constexpr MarketID():value_{max_value} {}
    constexpr explicit MarketID(uint16_t v):value_{v} {}
    constexpr MarketID(Enum v):value_{v} {}
    constexpr bool operator==(const MarketID& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const MarketID& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint16_t raw_value() const {return static_cast<uint16_t>(value_);}
    constexpr void raw_value(uint16_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr MarketID& operator=(Enum v) {value_ == v;return *this;}
    constexpr MarketID& operator=(const MarketID& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::XETR: return "XETR";
            case Enum::XVIE: return "XVIE";
            case Enum::XMAL: return "XMAL";
            case Enum::XBUL: return "XBUL";
            case Enum::XBUD: return "XBUD";
            case Enum::XLJU: return "XLJU";
            case Enum::XPRA: return "XPRA";
            case Enum::XZAG: return "XZAG";
            case Enum::XFRA: return "XFRA";
            case Enum::XDUS: return "XDUS";
            case Enum::XHAM: return "XHAM";
            case Enum::XHAN: return "XHAN";
            case Enum::XMUN: return "XMUN";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const MarketID& v){
    os << v.view();
    return os;
}
using MarketSegmentID = LittleEndian<int32_t, -2147483647, 2147483647, std::numeric_limits<int32_t>::min()>;
using MatchInstCrossID = LittleEndian<uint32_t, 0, 4294967294, 0xFFFFFFFF>;
struct MatchType {
    using value_type = uint8_t;
    enum Enum : value_type {
        Auto_match_incoming = 4,
        Cross_Auction = 5,
        Call_Auction = 7,
        Auto_match_resting = 11,
        Auto_match_at_mid_point = 12,
        Continuous_Auction = 14,
        Retail = 15,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "MatchType";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(4), static_cast<uint8_t>(5), static_cast<uint8_t>(7), static_cast<uint8_t>(11), static_cast<uint8_t>(12), static_cast<uint8_t>(14), static_cast<uint8_t>(15), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(4), static_cast<uint8_t>(5), static_cast<uint8_t>(7), static_cast<uint8_t>(11), static_cast<uint8_t>(12), static_cast<uint8_t>(14), static_cast<uint8_t>(15), });
    constexpr MatchType():value_{max_value} {}
    constexpr explicit MatchType(uint8_t v):value_{v} {}
    constexpr MatchType(Enum v):value_{v} {}
    constexpr bool operator==(const MatchType& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const MatchType& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr MatchType& operator=(Enum v) {value_ == v;return *this;}
    constexpr MatchType& operator=(const MatchType& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Auto_match_incoming: return "Auto_match_incoming";
            case Enum::Cross_Auction: return "Cross_Auction";
            case Enum::Call_Auction: return "Call_Auction";
            case Enum::Auto_match_resting: return "Auto_match_resting";
            case Enum::Auto_match_at_mid_point: return "Auto_match_at_mid_point";
            case Enum::Continuous_Auction: return "Continuous_Auction";
            case Enum::Retail: return "Retail";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const MatchType& v){
    os << v.view();
    return os;
}
struct MidPointType {
    using value_type = uint8_t;
    enum Enum : value_type {
        MidPoint = 1,
        MidPointSweep = 2,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "MidPointType";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), });
    constexpr MidPointType():value_{max_value} {}
    constexpr explicit MidPointType(uint8_t v):value_{v} {}
    constexpr MidPointType(Enum v):value_{v} {}
    constexpr bool operator==(const MidPointType& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const MidPointType& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr MidPointType& operator=(Enum v) {value_ == v;return *this;}
    constexpr MidPointType& operator=(const MidPointType& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::MidPoint: return "MidPoint";
            case Enum::MidPointSweep: return "MidPointSweep";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const MidPointType& v){
    os << v.view();
    return os;
}
using MinQty = LittleEndian<int64_t, -9223372036854775807LL, std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min(), 4>;
using MsgSeqNum = LittleEndian<uint32_t, 0, 4294967294, 0xFFFFFFFF>;
using MsgType = FixedLengthString<3, '\0', false>;
using NoAffectedOrders = LittleEndian<uint16_t, 0, 500, 0xFFFF>;
using NoFills = LittleEndian<uint8_t, 0_u8, 100_u8, 0xFF_u8>;
using NoPartitions = LittleEndian<uint8_t, 0_u8, 100_u8, 0xFF_u8>;
using NoSessions = LittleEndian<uint16_t, 1, 1000, 0xFFFF>;
struct OrdStatus {
    using value_type = char;
    enum Enum : value_type {
        New = '0',
        Partially_filled = '1',
        Filled = '2',
        Canceled = '4',
        Pending_Cancel = '6',
        Suspended = '9',
        Pending_New = 'A',
        Pending_Replace = 'E',
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "OrdStatus";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<char>('0'), static_cast<char>('1'), static_cast<char>('2'), static_cast<char>('4'), static_cast<char>('6'), static_cast<char>('9'), static_cast<char>('A'), static_cast<char>('E'), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<char>('0'), static_cast<char>('1'), static_cast<char>('2'), static_cast<char>('4'), static_cast<char>('6'), static_cast<char>('9'), static_cast<char>('A'), static_cast<char>('E'), });
    constexpr OrdStatus():value_{max_value} {}
    constexpr explicit OrdStatus(char v):value_{v} {}
    constexpr OrdStatus(Enum v):value_{v} {}
    constexpr bool operator==(const OrdStatus& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const OrdStatus& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr char raw_value() const {return static_cast<char>(value_);}
    constexpr void raw_value(char v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr OrdStatus& operator=(Enum v) {value_ == v;return *this;}
    constexpr OrdStatus& operator=(const OrdStatus& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::New: return "New";
            case Enum::Partially_filled: return "Partially_filled";
            case Enum::Filled: return "Filled";
            case Enum::Canceled: return "Canceled";
            case Enum::Pending_Cancel: return "Pending_Cancel";
            case Enum::Suspended: return "Suspended";
            case Enum::Pending_New: return "Pending_New";
            case Enum::Pending_Replace: return "Pending_Replace";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const OrdStatus& v){
    os << v.view();
    return os;
}
struct OrdType {
    using value_type = uint8_t;
    enum Enum : value_type {
        Market = 1,
        Limit = 2,
        Stop = 3,
        Stop_Limit = 4,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "OrdType";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(3), static_cast<uint8_t>(4), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(3), static_cast<uint8_t>(4), });
    constexpr OrdType():value_{max_value} {}
    constexpr explicit OrdType(uint8_t v):value_{v} {}
    constexpr OrdType(Enum v):value_{v} {}
    constexpr bool operator==(const OrdType& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const OrdType& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr OrdType& operator=(Enum v) {value_ == v;return *this;}
    constexpr OrdType& operator=(const OrdType& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Market: return "Market";
            case Enum::Limit: return "Limit";
            case Enum::Stop: return "Stop";
            case Enum::Stop_Limit: return "Stop_Limit";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const OrdType& v){
    os << v.view();
    return os;
}
using OrderID = LittleEndian<uint64_t, 0UL, 18446744073709551614UL, 0xFFFFFFFFFFFFFFFFUL>;
using OrderIDSfx = LittleEndian<uint32_t, 0, 4294967294, 0xFFFFFFFF>;
struct OrderOrigination {
    using value_type = uint8_t;
    enum Enum : value_type {
        Direct_access_customer = 5,
        Sponsored_access_customer = 105,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "OrderOrigination";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(5), static_cast<uint8_t>(105), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(5), static_cast<uint8_t>(105), });
    constexpr OrderOrigination():value_{max_value} {}
    constexpr explicit OrderOrigination(uint8_t v):value_{v} {}
    constexpr OrderOrigination(Enum v):value_{v} {}
    constexpr bool operator==(const OrderOrigination& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const OrderOrigination& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr OrderOrigination& operator=(Enum v) {value_ == v;return *this;}
    constexpr OrderOrigination& operator=(const OrderOrigination& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Direct_access_customer: return "Direct_access_customer";
            case Enum::Sponsored_access_customer: return "Sponsored_access_customer";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const OrderOrigination& v){
    os << v.view();
    return os;
}
using OrderQty = LittleEndian<int64_t, -9223372036854775807LL, std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min(), 4>;
using OrigClOrdID = LittleEndian<uint64_t, 0UL, 18446744073709551614UL, 0xFFFFFFFFFFFFFFFFUL>;
using Pad2 = FixedLengthString<2, '\0', false>;
using Pad3 = FixedLengthString<3, '\0', false>;
using Pad4 = FixedLengthString<4, '\0', false>;
using Pad4_1 = FixedLengthString<4, '\0', false>;
using Pad4_2 = FixedLengthString<4, '\0', false>;
using Pad4_3 = FixedLengthString<4, '\0', false>;
using Pad5 = FixedLengthString<5, '\0', false>;
using Pad6 = FixedLengthString<6, '\0', false>;
using Pad7 = FixedLengthString<7, '\0', false>;
using PartitionID = LittleEndian<uint16_t, 0, 65534, 0xFFFF>;
using PartyExecutingFirm = FixedLengthString<5, '\0', false>;
using PartyIDClientID = LittleEndian<uint64_t, 1UL, 18446744073709551614UL, 0xFFFFFFFFFFFFFFFFUL>;
using PartyIDExecutingTrader = LittleEndian<uint32_t, 0, 4294967294, 0xFFFFFFFF>;
using PartyIDExecutingUnit = LittleEndian<uint32_t, 0, 4294967294, 0xFFFFFFFF>;
using PartyIDSessionID = LittleEndian<uint32_t, 0, 4294967294, 0xFFFFFFFF>;
using PartyIDSponsoredAccessUnit = LittleEndian<uint32_t, 0, 4294967294, 0xFFFFFFFF>;
using PartyIdInvestmentDecisionMaker = LittleEndian<uint64_t, 1UL, 18446744073709551614UL, 0xFFFFFFFFFFFFFFFFUL>;
struct PartyIdInvestmentDecisionMakerQualifier {
    using value_type = uint8_t;
    enum Enum : value_type {
        Algo = 22,
        Human = 24,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "PartyIdInvestmentDecisionMakerQualifier";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(22), static_cast<uint8_t>(24), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(22), static_cast<uint8_t>(24), });
    constexpr PartyIdInvestmentDecisionMakerQualifier():value_{max_value} {}
    constexpr explicit PartyIdInvestmentDecisionMakerQualifier(uint8_t v):value_{v} {}
    constexpr PartyIdInvestmentDecisionMakerQualifier(Enum v):value_{v} {}
    constexpr bool operator==(const PartyIdInvestmentDecisionMakerQualifier& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const PartyIdInvestmentDecisionMakerQualifier& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr PartyIdInvestmentDecisionMakerQualifier& operator=(Enum v) {value_ == v;return *this;}
    constexpr PartyIdInvestmentDecisionMakerQualifier& operator=(const PartyIdInvestmentDecisionMakerQualifier& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Algo: return "Algo";
            case Enum::Human: return "Human";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const PartyIdInvestmentDecisionMakerQualifier& v){
    os << v.view();
    return os;
}
using PartySponsoredAccessUnit = FixedLengthString<30, '\0', false>;
using Password = FixedLengthString<32, '\0', false>;
using PegOffsetValueAbs = LittleEndian<int64_t, -9223372036854775807LL, std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min(), 8>;
using PegOffsetValuePct = LittleEndian<int64_t, -9223372036854775807LL, std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min(), 4>;
using Price = LittleEndian<int64_t, -9223372036854775807LL, std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min(), 8>;
using RequestTime = LittleEndian<uint64_t, 0UL, 18446744073709551614UL, 0xFFFFFFFFFFFFFFFFUL>;
using SecurityID = LittleEndian<int64_t, -9223372036854775807L, 9223372036854775807L, std::numeric_limits<int64_t>::min()>;
struct SelfMatchPreventionInstruction {
    using value_type = uint8_t;
    enum Enum : value_type {
        Cross_rejected_BU = 100,
        Cross_rejected_Market = 101,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "SelfMatchPreventionInstruction";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(100), static_cast<uint8_t>(101), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(100), static_cast<uint8_t>(101), });
    constexpr SelfMatchPreventionInstruction():value_{max_value} {}
    constexpr explicit SelfMatchPreventionInstruction(uint8_t v):value_{v} {}
    constexpr SelfMatchPreventionInstruction(Enum v):value_{v} {}
    constexpr bool operator==(const SelfMatchPreventionInstruction& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const SelfMatchPreventionInstruction& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr SelfMatchPreventionInstruction& operator=(Enum v) {value_ == v;return *this;}
    constexpr SelfMatchPreventionInstruction& operator=(const SelfMatchPreventionInstruction& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Cross_rejected_BU: return "Cross_rejected_BU";
            case Enum::Cross_rejected_Market: return "Cross_rejected_Market";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const SelfMatchPreventionInstruction& v){
    os << v.view();
    return os;
}
using SendingTime = LittleEndian<uint64_t, 0UL, 18446744073709551614UL, 0xFFFFFFFFFFFFFFFFUL>;
using SessionInstanceID = LittleEndian<uint32_t, 0, 4294967294, 0xFFFFFFFF>;
struct SessionMode {
    using value_type = uint8_t;
    enum Enum : value_type {
        ETI_HF = 1,
        ETI_LF = 2,
        GUI = 3,
        FIX_LF = 4,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "SessionMode";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(3), static_cast<uint8_t>(4), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(3), static_cast<uint8_t>(4), });
    constexpr SessionMode():value_{max_value} {}
    constexpr explicit SessionMode(uint8_t v):value_{v} {}
    constexpr SessionMode(Enum v):value_{v} {}
    constexpr bool operator==(const SessionMode& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const SessionMode& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr SessionMode& operator=(Enum v) {value_ == v;return *this;}
    constexpr SessionMode& operator=(const SessionMode& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::ETI_HF: return "ETI_HF";
            case Enum::ETI_LF: return "ETI_LF";
            case Enum::GUI: return "GUI";
            case Enum::FIX_LF: return "FIX_LF";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const SessionMode& v){
    os << v.view();
    return os;
}
struct SessionRejectReason {
    using value_type = uint32_t;
    enum Enum : value_type {
        Required_Tag_Missing = 1,
        Value_is_incorrect = 5,
        Decryption_problem = 7,
        Invalid_MsgID = 11,
        Incorrect_NumInGroup_count = 16,
        Other = 99,
        Exposure_Limit_Exceeded = 101,
        Service_Not_Available = 103,
        Outbound_conversion_error = 105,
        Heartbeat_Violation = 152,
        Internal_technical_error = 200,
        Validation_Error = 210,
        Session_Login_Limit_Reached = 217,
        Outstanding_Logins_Bu_Limit_Reached = 226,
        Outstanding_Logins_Session_Limit_Reached = 227,
        Password_Timestamp_Not_In_Grace_Period = 228,
    };
    static constexpr size_t size = 4;
    static constexpr char* name() {return "SessionRejectReason";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint32_t>(1), static_cast<uint32_t>(5), static_cast<uint32_t>(7), static_cast<uint32_t>(11), static_cast<uint32_t>(16), static_cast<uint32_t>(99), static_cast<uint32_t>(101), static_cast<uint32_t>(103), static_cast<uint32_t>(105), static_cast<uint32_t>(152), static_cast<uint32_t>(200), static_cast<uint32_t>(210), static_cast<uint32_t>(217), static_cast<uint32_t>(226), static_cast<uint32_t>(227), static_cast<uint32_t>(228), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint32_t>(1), static_cast<uint32_t>(5), static_cast<uint32_t>(7), static_cast<uint32_t>(11), static_cast<uint32_t>(16), static_cast<uint32_t>(99), static_cast<uint32_t>(101), static_cast<uint32_t>(103), static_cast<uint32_t>(105), static_cast<uint32_t>(152), static_cast<uint32_t>(200), static_cast<uint32_t>(210), static_cast<uint32_t>(217), static_cast<uint32_t>(226), static_cast<uint32_t>(227), static_cast<uint32_t>(228), });
    constexpr SessionRejectReason():value_{max_value} {}
    constexpr explicit SessionRejectReason(uint32_t v):value_{v} {}
    constexpr SessionRejectReason(Enum v):value_{v} {}
    constexpr bool operator==(const SessionRejectReason& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const SessionRejectReason& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint32_t raw_value() const {return static_cast<uint32_t>(value_);}
    constexpr void raw_value(uint32_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr SessionRejectReason& operator=(Enum v) {value_ == v;return *this;}
    constexpr SessionRejectReason& operator=(const SessionRejectReason& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Required_Tag_Missing: return "Required_Tag_Missing";
            case Enum::Value_is_incorrect: return "Value_is_incorrect";
            case Enum::Decryption_problem: return "Decryption_problem";
            case Enum::Invalid_MsgID: return "Invalid_MsgID";
            case Enum::Incorrect_NumInGroup_count: return "Incorrect_NumInGroup_count";
            case Enum::Other: return "Other";
            case Enum::Exposure_Limit_Exceeded: return "Exposure_Limit_Exceeded";
            case Enum::Service_Not_Available: return "Service_Not_Available";
            case Enum::Outbound_conversion_error: return "Outbound_conversion_error";
            case Enum::Heartbeat_Violation: return "Heartbeat_Violation";
            case Enum::Internal_technical_error: return "Internal_technical_error";
            case Enum::Validation_Error: return "Validation_Error";
            case Enum::Session_Login_Limit_Reached: return "Session_Login_Limit_Reached";
            case Enum::Outstanding_Logins_Bu_Limit_Reached: return "Outstanding_Logins_Bu_Limit_Reached";
            case Enum::Outstanding_Logins_Session_Limit_Reached: return "Outstanding_Logins_Session_Limit_Reached";
            case Enum::Password_Timestamp_Not_In_Grace_Period: return "Password_Timestamp_Not_In_Grace_Period";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const SessionRejectReason& v){
    os << v.view();
    return os;
}
struct SessionStatus {
    using value_type = uint8_t;
    enum Enum : value_type {
        Active = 0,
        Logout = 4,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "SessionStatus";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(0), static_cast<uint8_t>(4), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(0), static_cast<uint8_t>(4), });
    constexpr SessionStatus():value_{max_value} {}
    constexpr explicit SessionStatus(uint8_t v):value_{v} {}
    constexpr SessionStatus(Enum v):value_{v} {}
    constexpr bool operator==(const SessionStatus& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const SessionStatus& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr SessionStatus& operator=(Enum v) {value_ == v;return *this;}
    constexpr SessionStatus& operator=(const SessionStatus& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Active: return "Active";
            case Enum::Logout: return "Logout";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const SessionStatus& v){
    os << v.view();
    return os;
}
struct Side {
    using value_type = uint8_t;
    enum Enum : value_type {
        Buy = 1,
        Sell = 2,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "Side";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), });
    constexpr Side():value_{max_value} {}
    constexpr explicit Side(uint8_t v):value_{v} {}
    constexpr Side(Enum v):value_{v} {}
    constexpr bool operator==(const Side& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const Side& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr Side& operator=(Enum v) {value_ == v;return *this;}
    constexpr Side& operator=(const Side& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Buy: return "Buy";
            case Enum::Sell: return "Sell";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const Side& v){
    os << v.view();
    return os;
}
using StopPx = LittleEndian<int64_t, -9223372036854775807LL, std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min(), 8>;
struct TimeInForce {
    using value_type = uint8_t;
    enum Enum : value_type {
        Day = 0,
        GTC = 1,
        IOC = 3,
        FOK = 4,
        GTD = 6,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "TimeInForce";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(0), static_cast<uint8_t>(1), static_cast<uint8_t>(3), static_cast<uint8_t>(4), static_cast<uint8_t>(6), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(0), static_cast<uint8_t>(1), static_cast<uint8_t>(3), static_cast<uint8_t>(4), static_cast<uint8_t>(6), });
    constexpr TimeInForce():value_{max_value} {}
    constexpr explicit TimeInForce(uint8_t v):value_{v} {}
    constexpr TimeInForce(Enum v):value_{v} {}
    constexpr bool operator==(const TimeInForce& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const TimeInForce& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr TimeInForce& operator=(Enum v) {value_ == v;return *this;}
    constexpr TimeInForce& operator=(const TimeInForce& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Day: return "Day";
            case Enum::GTC: return "GTC";
            case Enum::IOC: return "IOC";
            case Enum::FOK: return "FOK";
            case Enum::GTD: return "GTD";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const TimeInForce& v){
    os << v.view();
    return os;
}
struct TradSesEvent {
    using value_type = uint8_t;
    enum Enum : value_type {
        End_of_Restatement = 103,
        End_of_Day_Service = 104,
        End_of_Order_book_synch = 107,
        Start_of_Order_book_synch = 108,
        Order_book_reset = 109,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "TradSesEvent";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(103), static_cast<uint8_t>(104), static_cast<uint8_t>(107), static_cast<uint8_t>(108), static_cast<uint8_t>(109), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(103), static_cast<uint8_t>(104), static_cast<uint8_t>(107), static_cast<uint8_t>(108), static_cast<uint8_t>(109), });
    constexpr TradSesEvent():value_{max_value} {}
    constexpr explicit TradSesEvent(uint8_t v):value_{v} {}
    constexpr TradSesEvent(Enum v):value_{v} {}
    constexpr bool operator==(const TradSesEvent& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const TradSesEvent& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr TradSesEvent& operator=(Enum v) {value_ == v;return *this;}
    constexpr TradSesEvent& operator=(const TradSesEvent& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::End_of_Restatement: return "End_of_Restatement";
            case Enum::End_of_Day_Service: return "End_of_Day_Service";
            case Enum::End_of_Order_book_synch: return "End_of_Order_book_synch";
            case Enum::Start_of_Order_book_synch: return "Start_of_Order_book_synch";
            case Enum::Order_book_reset: return "Order_book_reset";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const TradSesEvent& v){
    os << v.view();
    return os;
}
struct TradSesMode {
    using value_type = uint8_t;
    enum Enum : value_type {
        Testing = 1,
        Simulated = 2,
        Production = 3,
        Acceptance = 4,
        Disaster_Recovery = 5,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "TradSesMode";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(3), static_cast<uint8_t>(4), static_cast<uint8_t>(5), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(2), static_cast<uint8_t>(3), static_cast<uint8_t>(4), static_cast<uint8_t>(5), });
    constexpr TradSesMode():value_{max_value} {}
    constexpr explicit TradSesMode(uint8_t v):value_{v} {}
    constexpr TradSesMode(Enum v):value_{v} {}
    constexpr bool operator==(const TradSesMode& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const TradSesMode& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr TradSesMode& operator=(Enum v) {value_ == v;return *this;}
    constexpr TradSesMode& operator=(const TradSesMode& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Testing: return "Testing";
            case Enum::Simulated: return "Simulated";
            case Enum::Production: return "Production";
            case Enum::Acceptance: return "Acceptance";
            case Enum::Disaster_Recovery: return "Disaster_Recovery";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const TradSesMode& v){
    os << v.view();
    return os;
}
struct TradeAtCloseOptIn {
    using value_type = uint8_t;
    enum Enum : value_type {
        No = 0,
        Yes = 1,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "TradeAtCloseOptIn";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(0), static_cast<uint8_t>(1), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(0), static_cast<uint8_t>(1), });
    constexpr TradeAtCloseOptIn():value_{max_value} {}
    constexpr explicit TradeAtCloseOptIn(uint8_t v):value_{v} {}
    constexpr TradeAtCloseOptIn(Enum v):value_{v} {}
    constexpr bool operator==(const TradeAtCloseOptIn& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const TradeAtCloseOptIn& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr TradeAtCloseOptIn& operator=(Enum v) {value_ == v;return *this;}
    constexpr TradeAtCloseOptIn& operator=(const TradeAtCloseOptIn& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::No: return "No";
            case Enum::Yes: return "Yes";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const TradeAtCloseOptIn& v){
    os << v.view();
    return os;
}
using TradeDate = LittleEndian<uint32_t, 0, 99991231, 0xFFFFFFFF>;
struct TradingCapacity {
    using value_type = uint8_t;
    enum Enum : value_type {
        Customer = 1,
        Broker_dealer = 3,
        Principal = 5,
        Market_Maker = 6,
        Riskless_Principal = 9,
        Retail_Customer = 10,
        Retail_Market_Maker = 11,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "TradingCapacity";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(3), static_cast<uint8_t>(5), static_cast<uint8_t>(6), static_cast<uint8_t>(9), static_cast<uint8_t>(10), static_cast<uint8_t>(11), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(1), static_cast<uint8_t>(3), static_cast<uint8_t>(5), static_cast<uint8_t>(6), static_cast<uint8_t>(9), static_cast<uint8_t>(10), static_cast<uint8_t>(11), });
    constexpr TradingCapacity():value_{max_value} {}
    constexpr explicit TradingCapacity(uint8_t v):value_{v} {}
    constexpr TradingCapacity(Enum v):value_{v} {}
    constexpr bool operator==(const TradingCapacity& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const TradingCapacity& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr TradingCapacity& operator=(Enum v) {value_ == v;return *this;}
    constexpr TradingCapacity& operator=(const TradingCapacity& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Customer: return "Customer";
            case Enum::Broker_dealer: return "Broker_dealer";
            case Enum::Principal: return "Principal";
            case Enum::Market_Maker: return "Market_Maker";
            case Enum::Riskless_Principal: return "Riskless_Principal";
            case Enum::Retail_Customer: return "Retail_Customer";
            case Enum::Retail_Market_Maker: return "Retail_Market_Maker";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const TradingCapacity& v){
    os << v.view();
    return os;
}
struct TradingSessionSubID {
    using value_type = uint8_t;
    enum Enum : value_type {
        Opening_auction = 2,
        Closing_auction = 4,
        Intraday_Auction = 6,
        Any_Auction = 8,
        Special_Auction = 105,
        Main_Trading_Hours = 106,
        AVD_Opening_Auction = 107,
        AVD_Intraday_Auction = 108,
        AVD_Closing_Auction = 109,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "TradingSessionSubID";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(2), static_cast<uint8_t>(4), static_cast<uint8_t>(6), static_cast<uint8_t>(8), static_cast<uint8_t>(105), static_cast<uint8_t>(106), static_cast<uint8_t>(107), static_cast<uint8_t>(108), static_cast<uint8_t>(109), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(2), static_cast<uint8_t>(4), static_cast<uint8_t>(6), static_cast<uint8_t>(8), static_cast<uint8_t>(105), static_cast<uint8_t>(106), static_cast<uint8_t>(107), static_cast<uint8_t>(108), static_cast<uint8_t>(109), });
    constexpr TradingSessionSubID():value_{max_value} {}
    constexpr explicit TradingSessionSubID(uint8_t v):value_{v} {}
    constexpr TradingSessionSubID(Enum v):value_{v} {}
    constexpr bool operator==(const TradingSessionSubID& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const TradingSessionSubID& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr TradingSessionSubID& operator=(Enum v) {value_ == v;return *this;}
    constexpr TradingSessionSubID& operator=(const TradingSessionSubID& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Opening_auction: return "Opening_auction";
            case Enum::Closing_auction: return "Closing_auction";
            case Enum::Intraday_Auction: return "Intraday_Auction";
            case Enum::Any_Auction: return "Any_Auction";
            case Enum::Special_Auction: return "Special_Auction";
            case Enum::Main_Trading_Hours: return "Main_Trading_Hours";
            case Enum::AVD_Opening_Auction: return "AVD_Opening_Auction";
            case Enum::AVD_Intraday_Auction: return "AVD_Intraday_Auction";
            case Enum::AVD_Closing_Auction: return "AVD_Closing_Auction";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const TradingSessionSubID& v){
    os << v.view();
    return os;
}
struct Triggered {
    using value_type = uint8_t;
    enum Enum : value_type {
        Not_triggered = 0,
        Triggered_Stop = 1,
        Triggered_OCO = 2,
    };
    static constexpr size_t size = 1;
    static constexpr char* name() {return "Triggered";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<uint8_t>(0), static_cast<uint8_t>(1), static_cast<uint8_t>(2), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<uint8_t>(0), static_cast<uint8_t>(1), static_cast<uint8_t>(2), });
    constexpr Triggered():value_{max_value} {}
    constexpr explicit Triggered(uint8_t v):value_{v} {}
    constexpr Triggered(Enum v):value_{v} {}
    constexpr bool operator==(const Triggered& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const Triggered& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr uint8_t raw_value() const {return static_cast<uint8_t>(value_);}
    constexpr void raw_value(uint8_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr Triggered& operator=(Enum v) {value_ == v;return *this;}
    constexpr Triggered& operator=(const Triggered& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::Not_triggered: return "Not_triggered";
            case Enum::Triggered_Stop: return "Triggered_Stop";
            case Enum::Triggered_OCO: return "Triggered_OCO";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const Triggered& v){
    os << v.view();
    return os;
}
using VarText = FixedLengthString<2000, '\0', false>;
using VarTextLen = LittleEndian<uint16_t, 0, 2000, 0xFFFF>;
struct TemplateID {
    using value_type = int16_t;
    enum Enum : value_type {
        DeleteOrderBroadcast = 10902,
        ForcedLogoutNotification = 10012,
        Heartbeat = 10011,
        HeartbeatNotification = 10023,
        LogonRequest = 10000,
        LogonResponse = 10001,
        LogoutRequest = 10002,
        LogoutResponse = 10003,
        OrderExecReportBroadcast = 10901,
        PartitionListNotification = 10037,
        Reject = 10010,
        SessionListNotification = 10036,
        SessionStatusBroadcast = 10903,
        TrailingStopUpdateNotification = 10904,
    };
    static constexpr size_t size = 2;
    static constexpr char* name() {return "TemplateID";}
    static constexpr value_type min_value = std::min<value_type>({static_cast<int16_t>(10902), static_cast<int16_t>(10012), static_cast<int16_t>(10011), static_cast<int16_t>(10023), static_cast<int16_t>(10000), static_cast<int16_t>(10001), static_cast<int16_t>(10002), static_cast<int16_t>(10003), static_cast<int16_t>(10901), static_cast<int16_t>(10037), static_cast<int16_t>(10010), static_cast<int16_t>(10036), static_cast<int16_t>(10903), static_cast<int16_t>(10904), });
    static constexpr value_type max_value = std::max<value_type>({static_cast<int16_t>(10902), static_cast<int16_t>(10012), static_cast<int16_t>(10011), static_cast<int16_t>(10023), static_cast<int16_t>(10000), static_cast<int16_t>(10001), static_cast<int16_t>(10002), static_cast<int16_t>(10003), static_cast<int16_t>(10901), static_cast<int16_t>(10037), static_cast<int16_t>(10010), static_cast<int16_t>(10036), static_cast<int16_t>(10903), static_cast<int16_t>(10904), });
    constexpr TemplateID():value_{max_value} {}
    constexpr explicit TemplateID(int16_t v):value_{v} {}
    constexpr TemplateID(Enum v):value_{v} {}
    constexpr bool operator==(const TemplateID& rhs) const {return value_ == rhs.value_;}
    constexpr bool operator!=(const TemplateID& rhs) const {return value_ != rhs.value_;}
    constexpr bool operator!=(Enum v) const {return value_ != v;}
    constexpr Enum value() const {return value_;}
    constexpr int16_t raw_value() const {return static_cast<int16_t>(value_);}
    constexpr void raw_value(int16_t v) {value_ = Enum(v);}
    constexpr void set(Enum v) {value_ = v;}
    constexpr TemplateID& operator=(Enum v) {value_ == v;return *this;}
    constexpr TemplateID& operator=(const TemplateID& rhs) = default;
    constexpr int length() const {return sizeof(value_);}
    constexpr const std::string_view view() const {
        switch(value_) {
            case Enum::DeleteOrderBroadcast: return "DeleteOrderBroadcast";
            case Enum::ForcedLogoutNotification: return "ForcedLogoutNotification";
            case Enum::Heartbeat: return "Heartbeat";
            case Enum::HeartbeatNotification: return "HeartbeatNotification";
            case Enum::LogonRequest: return "LogonRequest";
            case Enum::LogonResponse: return "LogonResponse";
            case Enum::LogoutRequest: return "LogoutRequest";
            case Enum::LogoutResponse: return "LogoutResponse";
            case Enum::OrderExecReportBroadcast: return "OrderExecReportBroadcast";
            case Enum::PartitionListNotification: return "PartitionListNotification";
            case Enum::Reject: return "Reject";
            case Enum::SessionListNotification: return "SessionListNotification";
            case Enum::SessionStatusBroadcast: return "SessionStatusBroadcast";
            case Enum::TrailingStopUpdateNotification: return "TrailingStopUpdateNotification";
        }
        return "";
    }
    Enum value_{max_value};
};

template <typename ostreamT>
inline ostreamT& operator<<(ostreamT& os, const TemplateID& v){
    os << v.view();
    return os;
}
#pragma pack(1)
struct AffectedOrdGrpComp {
    AffectedOrderID affectedOrderID;
    AffectedClOrdID affectedClOrdID;
    AffectedOrigClOrdID affectedOrigClOrdID;
    SecurityID securityID;
    OrderIDSfx orderIDSfx;
    PartyIDSessionID partyIDSessionID;
    PartyIDExecutingTrader partyIDExecutingTrader;
    OrdStatus ordStatus{OrdStatus::null};
    ExecType execType{ExecType::null};
    AffectedFIXClOrdID affectedFIXClOrdID;
    AffectedFIXOrigClOrdID affectedFIXOrigClOrdID;
    Pad2 pad2;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(AffectedOrdGrpComp);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const AffectedOrdGrpComp& msg) {
    os << "affectedOrderID=" << msg.affectedOrderID << ";"
       << "affectedClOrdID=" << msg.affectedClOrdID << ";"
       << "affectedOrigClOrdID=" << msg.affectedOrigClOrdID << ";"
       << "securityID=" << msg.securityID << ";"
       << "orderIDSfx=" << msg.orderIDSfx << ";"
       << "partyIDSessionID=" << msg.partyIDSessionID << ";"
       << "partyIDExecutingTrader=" << msg.partyIDExecutingTrader << ";"
       << "ordStatus=" << msg.ordStatus << ";"
       << "execType=" << msg.execType << ";"
       << "affectedFIXClOrdID=" << msg.affectedFIXClOrdID << ";"
       << "affectedFIXOrigClOrdID=" << msg.affectedFIXOrigClOrdID << ";"
       << "pad2=" << msg.pad2 << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct FillsGrpComp {
    FillPx fillPx;
    FillQty fillQty;
    FillMatchID fillMatchID;
    FillExecID fillExecID;
    FillLiquidityInd fillLiquidityInd{FillLiquidityInd::null};
    Pad7 pad7;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(FillsGrpComp);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const FillsGrpComp& msg) {
    os << "fillPx=" << msg.fillPx << ";"
       << "fillQty=" << msg.fillQty << ";"
       << "fillMatchID=" << msg.fillMatchID << ";"
       << "fillExecID=" << msg.fillExecID << ";"
       << "fillLiquidityInd=" << msg.fillLiquidityInd << ";"
       << "pad7=" << msg.pad7 << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct MessageHeaderInComp {
    BodyLen bodyLen;
    TemplateID templateID{TemplateID::null};
    Pad2 pad2;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(MessageHeaderInComp);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const MessageHeaderInComp& msg) {
    os << "bodyLen=" << msg.bodyLen << ";"
       << "templateID=" << msg.templateID << ";"
       << "pad2=" << msg.pad2 << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct MessageHeaderOutComp {
    BodyLen bodyLen;
    TemplateID templateID{TemplateID::null};
    Pad2 pad2;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(MessageHeaderOutComp);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const MessageHeaderOutComp& msg) {
    os << "bodyLen=" << msg.bodyLen << ";"
       << "templateID=" << msg.templateID << ";"
       << "pad2=" << msg.pad2 << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct NotifHeaderComp {
    SendingTime sendingTime;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(NotifHeaderComp);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const NotifHeaderComp& msg) {
    os << "sendingTime=" << msg.sendingTime << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct PartitionGrpComp {
    PartitionID partitionID;
    Pad6 pad6;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(PartitionGrpComp);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const PartitionGrpComp& msg) {
    os << "partitionID=" << msg.partitionID << ";"
       << "pad6=" << msg.pad6 << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct RBCHeaderComp {
    SendingTime sendingTime;
    PartyIDExecutingUnit partyIDExecutingUnit;
    PartitionID partitionID;
    ApplID applID{ApplID::null};
    LastFragment lastFragment{LastFragment::null};
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(RBCHeaderComp);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const RBCHeaderComp& msg) {
    os << "sendingTime=" << msg.sendingTime << ";"
       << "partyIDExecutingUnit=" << msg.partyIDExecutingUnit << ";"
       << "partitionID=" << msg.partitionID << ";"
       << "applID=" << msg.applID << ";"
       << "lastFragment=" << msg.lastFragment << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct RequestHeaderComp {
    MsgSeqNum msgSeqNum;
    Pad4 pad4;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(RequestHeaderComp);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const RequestHeaderComp& msg) {
    os << "msgSeqNum=" << msg.msgSeqNum << ";"
       << "pad4=" << msg.pad4 << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct ResponseHeaderComp {
    RequestTime requestTime;
    SendingTime sendingTime;
    MsgSeqNum msgSeqNum;
    LastFragment lastFragment{LastFragment::null};
    Pad3 pad3;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(ResponseHeaderComp);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const ResponseHeaderComp& msg) {
    os << "requestTime=" << msg.requestTime << ";"
       << "sendingTime=" << msg.sendingTime << ";"
       << "msgSeqNum=" << msg.msgSeqNum << ";"
       << "lastFragment=" << msg.lastFragment << ";"
       << "pad3=" << msg.pad3 << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct SessionsGrpComp {
    PartyIDSessionID partyIDSessionID;
    PartyIDExecutingUnit partyIDExecutingUnit;
    PartyIDSponsoredAccessUnit partyIDSponsoredAccessUnit;
    SessionMode sessionMode{SessionMode::null};
    PartyExecutingFirm partyExecutingFirm;
    PartySponsoredAccessUnit partySponsoredAccessUnit;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(SessionsGrpComp);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const SessionsGrpComp& msg) {
    os << "partyIDSessionID=" << msg.partyIDSessionID << ";"
       << "partyIDExecutingUnit=" << msg.partyIDExecutingUnit << ";"
       << "partyIDSponsoredAccessUnit=" << msg.partyIDSponsoredAccessUnit << ";"
       << "sessionMode=" << msg.sessionMode << ";"
       << "partyExecutingFirm=" << msg.partyExecutingFirm << ";"
       << "partySponsoredAccessUnit=" << msg.partySponsoredAccessUnit << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct DeleteOrderBroadcast {
    MessageHeaderOutComp messageHeaderOut;
    RBCHeaderComp rBCHeader;
    ExecID execID;
    MarketSegmentID marketSegmentID;
    NoAffectedOrders noAffectedOrders;
    Pad2 pad2;
    BlockRef<AffectedOrdGrpComp> affectedOrdGrp() {return BlockRef<AffectedOrdGrpComp>(begin()+size(), noAffectedOrders);}
    BlockRef<AffectedOrdGrpComp> affectedOrdGrp() const {return BlockRef<AffectedOrdGrpComp>(begin()+size(), noAffectedOrders);}
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(DeleteOrderBroadcast);}
    size_t var_size() const {return affectedOrdGrp().end()-begin();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const DeleteOrderBroadcast& msg) {
    os << "messageHeaderOut=" << msg.messageHeaderOut << ";"
       << "rBCHeader=" << msg.rBCHeader << ";"
       << "execID=" << msg.execID << ";"
       << "marketSegmentID=" << msg.marketSegmentID << ";"
       << "noAffectedOrders=" << msg.noAffectedOrders << ";"
       << "pad2=" << msg.pad2 << ";"
       << "affectedOrdGrp=" << const_cast<DeleteOrderBroadcast&>(msg).affectedOrdGrp() << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct ForcedLogoutNotification {
    MessageHeaderOutComp messageHeaderOut;
    NotifHeaderComp notifHeader;
    VarTextLen varTextLen;
    BlockRef<VarText> varText() {return BlockRef<VarText>(begin()+size(), varTextLen);}
    BlockRef<VarText> varText() const {return BlockRef<VarText>(begin()+size(), varTextLen);}
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(ForcedLogoutNotification);}
    size_t var_size() const {return varText().end()-begin();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const ForcedLogoutNotification& msg) {
    os << "messageHeaderOut=" << msg.messageHeaderOut << ";"
       << "notifHeader=" << msg.notifHeader << ";"
       << "varTextLen=" << msg.varTextLen << ";"
       << "varText=" << const_cast<ForcedLogoutNotification&>(msg).varText() << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct Heartbeat {
    MessageHeaderInComp messageHeaderIn;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(Heartbeat);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const Heartbeat& msg) {
    os << "messageHeaderIn=" << msg.messageHeaderIn << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct HeartbeatNotification {
    MessageHeaderOutComp messageHeaderOut;
    NotifHeaderComp notifHeader;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(HeartbeatNotification);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const HeartbeatNotification& msg) {
    os << "messageHeaderOut=" << msg.messageHeaderOut << ";"
       << "notifHeader=" << msg.notifHeader << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct LogonRequest {
    MessageHeaderInComp messageHeaderIn;
    RequestHeaderComp requestHeader;
    HeartBtInt heartBtInt;
    PartyIDSessionID partyIDSessionID;
    DefaultCstmApplVerID defaultCstmApplVerID;
    Password password;
    Pad2 pad2;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(LogonRequest);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const LogonRequest& msg) {
    os << "messageHeaderIn=" << msg.messageHeaderIn << ";"
       << "requestHeader=" << msg.requestHeader << ";"
       << "heartBtInt=" << msg.heartBtInt << ";"
       << "partyIDSessionID=" << msg.partyIDSessionID << ";"
       << "defaultCstmApplVerID=" << msg.defaultCstmApplVerID << ";"
       << "password=" << msg.password << ";"
       << "pad2=" << msg.pad2 << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct LogonResponse {
    MessageHeaderOutComp messageHeaderOut;
    ResponseHeaderComp responseHeader;
    HeartBtInt heartBtInt;
    SessionInstanceID sessionInstanceID;
    MarketID marketID{MarketID::null};
    TradSesMode tradSesMode{TradSesMode::null};
    DefaultCstmApplVerID defaultCstmApplVerID;
    DefaultCstmApplVerSubID defaultCstmApplVerSubID;
    Pad2 pad2;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(LogonResponse);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const LogonResponse& msg) {
    os << "messageHeaderOut=" << msg.messageHeaderOut << ";"
       << "responseHeader=" << msg.responseHeader << ";"
       << "heartBtInt=" << msg.heartBtInt << ";"
       << "sessionInstanceID=" << msg.sessionInstanceID << ";"
       << "marketID=" << msg.marketID << ";"
       << "tradSesMode=" << msg.tradSesMode << ";"
       << "defaultCstmApplVerID=" << msg.defaultCstmApplVerID << ";"
       << "defaultCstmApplVerSubID=" << msg.defaultCstmApplVerSubID << ";"
       << "pad2=" << msg.pad2 << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct LogoutRequest {
    MessageHeaderInComp messageHeaderIn;
    RequestHeaderComp requestHeader;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(LogoutRequest);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const LogoutRequest& msg) {
    os << "messageHeaderIn=" << msg.messageHeaderIn << ";"
       << "requestHeader=" << msg.requestHeader << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct LogoutResponse {
    MessageHeaderOutComp messageHeaderOut;
    ResponseHeaderComp responseHeader;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(LogoutResponse);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const LogoutResponse& msg) {
    os << "messageHeaderOut=" << msg.messageHeaderOut << ";"
       << "responseHeader=" << msg.responseHeader << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct OrderExecReportBroadcast {
    MessageHeaderOutComp messageHeaderOut;
    RBCHeaderComp rBCHeader;
    OrderID orderID;
    ClOrdID clOrdID;
    OrigClOrdID origClOrdID;
    SecurityID securityID;
    ExecID execID;
    Price price;
    StopPx stopPx;
    LeavesQty leavesQty;
    CumQty cumQty;
    CxlQty cxlQty;
    OrderQty orderQty;
    MinQty minQty;
    DisplayQty displayQty;
    PegOffsetValueAbs pegOffsetValueAbs;
    PegOffsetValuePct pegOffsetValuePct;
    PartyIDClientID partyIDClientID;
    PartyIdInvestmentDecisionMaker partyIdInvestmentDecisionMaker;
    ExecutingTrader executingTrader;
    BrokerInternalizationID brokerInternalizationID;
    MarketSegmentID marketSegmentID;
    OrderIDSfx orderIDSfx;
    MatchInstCrossID matchInstCrossID;
    ExpireDate expireDate;
    PartyIDSessionID partyIDSessionID;
    PartyIDExecutingTrader partyIDExecutingTrader;
    OrdStatus ordStatus{OrdStatus::null};
    ExecType execType{ExecType::null};
    Side side{Side::null};
    OrdType ordType{OrdType::null};
    MatchType matchType{MatchType::null};
    TradingCapacity tradingCapacity{TradingCapacity::null};
    TimeInForce timeInForce{TimeInForce::null};
    ExecInst execInst{ExecInst::null};
    Triggered triggered{Triggered::null};
    TradingSessionSubID tradingSessionSubID{TradingSessionSubID::null};
    ApplSeqIndicator applSeqIndicator{ApplSeqIndicator::null};
    SelfMatchPreventionInstruction selfMatchPreventionInstruction{SelfMatchPreventionInstruction::null};
    CrossMatchInstruction crossMatchInstruction{CrossMatchInstruction::null};
    PartyIdInvestmentDecisionMakerQualifier partyIdInvestmentDecisionMakerQualifier{PartyIdInvestmentDecisionMakerQualifier::null};
    ExecutingTraderQualifier executingTraderQualifier{ExecutingTraderQualifier::null};
    NoFills noFills;
    CrossedIndicator crossedIndicator{CrossedIndicator::null};
    CustOrderHandlingInst custOrderHandlingInst;
    MidPointType midPointType{MidPointType::null};
    TradeAtCloseOptIn tradeAtCloseOptIn{TradeAtCloseOptIn::null};
    OrderOrigination orderOrigination{OrderOrigination::null};
    FreeText1 freeText1;
    FreeText2 freeText2;
    FreeText4 freeText4;
    FIXClOrdID fIXClOrdID;
    FIXOrigClOrdID fIXOrigClOrdID;
    Pad7 pad7;
    BlockRef<FillsGrpComp> fillsGrp() {return BlockRef<FillsGrpComp>(begin()+size(), noFills);}
    BlockRef<FillsGrpComp> fillsGrp() const {return BlockRef<FillsGrpComp>(begin()+size(), noFills);}
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(OrderExecReportBroadcast);}
    size_t var_size() const {return fillsGrp().end()-begin();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const OrderExecReportBroadcast& msg) {
    os << "messageHeaderOut=" << msg.messageHeaderOut << ";"
       << "rBCHeader=" << msg.rBCHeader << ";"
       << "orderID=" << msg.orderID << ";"
       << "clOrdID=" << msg.clOrdID << ";"
       << "origClOrdID=" << msg.origClOrdID << ";"
       << "securityID=" << msg.securityID << ";"
       << "execID=" << msg.execID << ";"
       << "price=" << msg.price << ";"
       << "stopPx=" << msg.stopPx << ";"
       << "leavesQty=" << msg.leavesQty << ";"
       << "cumQty=" << msg.cumQty << ";"
       << "cxlQty=" << msg.cxlQty << ";"
       << "orderQty=" << msg.orderQty << ";"
       << "minQty=" << msg.minQty << ";"
       << "displayQty=" << msg.displayQty << ";"
       << "pegOffsetValueAbs=" << msg.pegOffsetValueAbs << ";"
       << "pegOffsetValuePct=" << msg.pegOffsetValuePct << ";"
       << "partyIDClientID=" << msg.partyIDClientID << ";"
       << "partyIdInvestmentDecisionMaker=" << msg.partyIdInvestmentDecisionMaker << ";"
       << "executingTrader=" << msg.executingTrader << ";"
       << "brokerInternalizationID=" << msg.brokerInternalizationID << ";"
       << "marketSegmentID=" << msg.marketSegmentID << ";"
       << "orderIDSfx=" << msg.orderIDSfx << ";"
       << "matchInstCrossID=" << msg.matchInstCrossID << ";"
       << "expireDate=" << msg.expireDate << ";"
       << "partyIDSessionID=" << msg.partyIDSessionID << ";"
       << "partyIDExecutingTrader=" << msg.partyIDExecutingTrader << ";"
       << "ordStatus=" << msg.ordStatus << ";"
       << "execType=" << msg.execType << ";"
       << "side=" << msg.side << ";"
       << "ordType=" << msg.ordType << ";"
       << "matchType=" << msg.matchType << ";"
       << "tradingCapacity=" << msg.tradingCapacity << ";"
       << "timeInForce=" << msg.timeInForce << ";"
       << "execInst=" << msg.execInst << ";"
       << "triggered=" << msg.triggered << ";"
       << "tradingSessionSubID=" << msg.tradingSessionSubID << ";"
       << "applSeqIndicator=" << msg.applSeqIndicator << ";"
       << "selfMatchPreventionInstruction=" << msg.selfMatchPreventionInstruction << ";"
       << "crossMatchInstruction=" << msg.crossMatchInstruction << ";"
       << "partyIdInvestmentDecisionMakerQualifier=" << msg.partyIdInvestmentDecisionMakerQualifier << ";"
       << "executingTraderQualifier=" << msg.executingTraderQualifier << ";"
       << "noFills=" << msg.noFills << ";"
       << "crossedIndicator=" << msg.crossedIndicator << ";"
       << "custOrderHandlingInst=" << msg.custOrderHandlingInst << ";"
       << "midPointType=" << msg.midPointType << ";"
       << "tradeAtCloseOptIn=" << msg.tradeAtCloseOptIn << ";"
       << "orderOrigination=" << msg.orderOrigination << ";"
       << "freeText1=" << msg.freeText1 << ";"
       << "freeText2=" << msg.freeText2 << ";"
       << "freeText4=" << msg.freeText4 << ";"
       << "fIXClOrdID=" << msg.fIXClOrdID << ";"
       << "fIXOrigClOrdID=" << msg.fIXOrigClOrdID << ";"
       << "pad7=" << msg.pad7 << ";"
       << "fillsGrp=" << const_cast<OrderExecReportBroadcast&>(msg).fillsGrp() << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct PartitionListNotification {
    MessageHeaderOutComp messageHeaderOut;
    NotifHeaderComp notifHeader;
    NoPartitions noPartitions;
    Pad7 pad7;
    BlockRef<PartitionGrpComp> partitionGrp() {return BlockRef<PartitionGrpComp>(begin()+size(), noPartitions);}
    BlockRef<PartitionGrpComp> partitionGrp() const {return BlockRef<PartitionGrpComp>(begin()+size(), noPartitions);}
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(PartitionListNotification);}
    size_t var_size() const {return partitionGrp().end()-begin();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const PartitionListNotification& msg) {
    os << "messageHeaderOut=" << msg.messageHeaderOut << ";"
       << "notifHeader=" << msg.notifHeader << ";"
       << "noPartitions=" << msg.noPartitions << ";"
       << "pad7=" << msg.pad7 << ";"
       << "partitionGrp=" << const_cast<PartitionListNotification&>(msg).partitionGrp() << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct Reject {
    MessageHeaderOutComp messageHeaderOut;
    ResponseHeaderComp responseHeader;
    SessionRejectReason sessionRejectReason{SessionRejectReason::null};
    VarTextLen varTextLen;
    SessionStatus sessionStatus{SessionStatus::null};
    BlockRef<VarText> varText() {return BlockRef<VarText>(begin()+size(), varTextLen);}
    BlockRef<VarText> varText() const {return BlockRef<VarText>(begin()+size(), varTextLen);}
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(Reject);}
    size_t var_size() const {return varText().end()-begin();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const Reject& msg) {
    os << "messageHeaderOut=" << msg.messageHeaderOut << ";"
       << "responseHeader=" << msg.responseHeader << ";"
       << "sessionRejectReason=" << msg.sessionRejectReason << ";"
       << "varTextLen=" << msg.varTextLen << ";"
       << "sessionStatus=" << msg.sessionStatus << ";"
       << "varText=" << const_cast<Reject&>(msg).varText() << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct SessionListNotification {
    MessageHeaderOutComp messageHeaderOut;
    NotifHeaderComp notifHeader;
    NoSessions noSessions;
    Pad6 pad6;
    BlockRef<SessionsGrpComp> sessionsGrp() {return BlockRef<SessionsGrpComp>(begin()+size(), noSessions);}
    BlockRef<SessionsGrpComp> sessionsGrp() const {return BlockRef<SessionsGrpComp>(begin()+size(), noSessions);}
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(SessionListNotification);}
    size_t var_size() const {return sessionsGrp().end()-begin();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const SessionListNotification& msg) {
    os << "messageHeaderOut=" << msg.messageHeaderOut << ";"
       << "notifHeader=" << msg.notifHeader << ";"
       << "noSessions=" << msg.noSessions << ";"
       << "pad6=" << msg.pad6 << ";"
       << "sessionsGrp=" << const_cast<SessionListNotification&>(msg).sessionsGrp() << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct SessionStatusBroadcast {
    MessageHeaderOutComp messageHeaderOut;
    RBCHeaderComp rBCHeader;
    TradeDate tradeDate;
    MarketSegmentID marketSegmentID;
    TradSesEvent tradSesEvent{TradSesEvent::null};
    Pad7 pad7;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(SessionStatusBroadcast);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const SessionStatusBroadcast& msg) {
    os << "messageHeaderOut=" << msg.messageHeaderOut << ";"
       << "rBCHeader=" << msg.rBCHeader << ";"
       << "tradeDate=" << msg.tradeDate << ";"
       << "marketSegmentID=" << msg.marketSegmentID << ";"
       << "tradSesEvent=" << msg.tradSesEvent << ";"
       << "pad7=" << msg.pad7 << ";"
       << "}";
    return os;
}
#pragma pack(1)
struct TrailingStopUpdateNotification {
    MessageHeaderOutComp messageHeaderOut;
    RBCHeaderComp rBCHeader;
    OrderID orderID;
    ClOrdID clOrdID;
    OrigClOrdID origClOrdID;
    SecurityID securityID;
    ExecID execID;
    StopPx stopPx;
    OrderQty orderQty;
    OrderIDSfx orderIDSfx;
    MarketSegmentID marketSegmentID;
    Side side{Side::null};
    FIXClOrdID fIXClOrdID;
    FIXOrigClOrdID fIXOrigClOrdID;
    Pad7 pad7;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<char*>(this);}
    char* end() {return begin()+length();}
    const char* cend() const {return begin()+length();}
    size_t size() const {return sizeof(TrailingStopUpdateNotification);}
    size_t var_size() const {return size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const TrailingStopUpdateNotification& msg) {
    os << "messageHeaderOut=" << msg.messageHeaderOut << ";"
       << "rBCHeader=" << msg.rBCHeader << ";"
       << "orderID=" << msg.orderID << ";"
       << "clOrdID=" << msg.clOrdID << ";"
       << "origClOrdID=" << msg.origClOrdID << ";"
       << "securityID=" << msg.securityID << ";"
       << "execID=" << msg.execID << ";"
       << "stopPx=" << msg.stopPx << ";"
       << "orderQty=" << msg.orderQty << ";"
       << "orderIDSfx=" << msg.orderIDSfx << ";"
       << "marketSegmentID=" << msg.marketSegmentID << ";"
       << "side=" << msg.side << ";"
       << "fIXClOrdID=" << msg.fIXClOrdID << ";"
       << "fIXOrigClOrdID=" << msg.fIXOrigClOrdID << ";"
       << "pad7=" << msg.pad7 << ";"
       << "}";
    return os;
}
} // end of namespace DBEDCI_141_Cash


