package eb_lang.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int EBAlias = 0;
  public static final int EBArray = 1;
  public static final int EBBitField = 2;
  public static final int EBBitFieldMember = 3;
  public static final int EBCPP = 4;
  public static final int EBChar = 5;
  public static final int EBCharLiteral = 6;
  public static final int EBComment = 7;
  public static final int EBEmptyStatement = 8;
  public static final int EBEnum = 9;
  public static final int EBFixedLenghString = 10;
  public static final int EBFloatDecimal = 11;
  public static final int EBIIdentifierConcept = 12;
  public static final int EBInclude = 13;
  public static final int EBInt16 = 14;
  public static final int EBInt32 = 15;
  public static final int EBInt64 = 16;
  public static final int EBInt8 = 17;
  public static final int EBIntKVPair = 18;
  public static final int EBIntLiteral = 19;
  public static final int EBIntType = 20;
  public static final int EBMessage = 21;
  public static final int EBMessageArrayMember = 22;
  public static final int EBMessageEntryMember = 23;
  public static final int EBMessageFixedBitsMember = 24;
  public static final int EBMessageMember = 25;
  public static final int EBMessageMemberVar = 26;
  public static final int EBMessageMemberVarNoType = 27;
  public static final int EBMessagePresenceByBitMember = 28;
  public static final int EBMessagePresenceByEnumEntryMember = 29;
  public static final int EBMessagePresenceByEnumMember = 30;
  public static final int EBMessagePresenceByLengthFieldMember = 31;
  public static final int EBMessagePresenceByValueFieldMember = 32;
  public static final int EBMessageVarArrayMember = 33;
  public static final int EBMessageVarStrMember = 34;
  public static final int EBNumberLiteral = 35;
  public static final int EBPrimitive = 36;
  public static final int EBPrimitiveType = 37;
  public static final int EBProtocol = 38;
  public static final int EBPython = 39;
  public static final int EBStatement = 40;
  public static final int EBTypeStatement = 41;
  public static final int EBUInt16 = 42;
  public static final int EBUInt32 = 43;
  public static final int EBUInt64 = 44;
  public static final int EBUInt8 = 45;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x59242254602f42f3L, 0xab3adc203eb4cc03L);
    builder.put(0x3e5cab00be01a366L, EBAlias);
    builder.put(0x3fa729f234141fd1L, EBArray);
    builder.put(0x726a4e86e241698fL, EBBitField);
    builder.put(0x726a4e86e2416997L, EBBitFieldMember);
    builder.put(0x726a4e86e24169c4L, EBCPP);
    builder.put(0x726a4e86e23f3d15L, EBChar);
    builder.put(0x726a4e86e23f3d18L, EBCharLiteral);
    builder.put(0x726a4e86e24169a5L, EBComment);
    builder.put(0x726a4e86e23f3cfeL, EBEmptyStatement);
    builder.put(0x726a4e86e23f3d0dL, EBEnum);
    builder.put(0x726a4e86e24124b5L, EBFixedLenghString);
    builder.put(0x1314ce5d5c778a82L, EBFloatDecimal);
    builder.put(0x726a4e86e23e7834L, EBIIdentifierConcept);
    builder.put(0x5300c8f52845c9aaL, EBInclude);
    builder.put(0x726a4e86e24124aeL, EBInt16);
    builder.put(0x726a4e86e24124afL, EBInt32);
    builder.put(0x726a4e86e24124b0L, EBInt64);
    builder.put(0x726a4e86e23f3d14L, EBInt8);
    builder.put(0x726a4e86e23f3d1dL, EBIntKVPair);
    builder.put(0x726a4e86e23f3d16L, EBIntLiteral);
    builder.put(0x78f986b06f13f864L, EBIntType);
    builder.put(0x726a4e86e2416a26L, EBMessage);
    builder.put(0x3fa729f2352470a3L, EBMessageArrayMember);
    builder.put(0x726a4e86e2416a34L, EBMessageEntryMember);
    builder.put(0x3fa729f2343219fcL, EBMessageFixedBitsMember);
    builder.put(0x726a4e86e2416a2aL, EBMessageMember);
    builder.put(0x54785f5b332a751cL, EBMessageMemberVar);
    builder.put(0x2a420f705fa9e8eaL, EBMessageMemberVarNoType);
    builder.put(0x7c7761e15adb3d7fL, EBMessagePresenceByBitMember);
    builder.put(0xd07fe56f4676460L, EBMessagePresenceByEnumEntryMember);
    builder.put(0x3fa729f235495b10L, EBMessagePresenceByEnumMember);
    builder.put(0x3fa729f2355ef0eeL, EBMessagePresenceByLengthFieldMember);
    builder.put(0x3fa729f2354a0048L, EBMessagePresenceByValueFieldMember);
    builder.put(0x726a4e86e2416a29L, EBMessageVarArrayMember);
    builder.put(0x4f03300badfbfa51L, EBMessageVarStrMember);
    builder.put(0x726a4e86e23f3d17L, EBNumberLiteral);
    builder.put(0x726a4e86e2416a06L, EBPrimitive);
    builder.put(0x726a4e86e23f3d10L, EBPrimitiveType);
    builder.put(0x726a4e86e23f3cf6L, EBProtocol);
    builder.put(0x726a4e86e2416a09L, EBPython);
    builder.put(0x726a4e86e23f3cf2L, EBStatement);
    builder.put(0x726a4e86e23f3cf3L, EBTypeStatement);
    builder.put(0x726a4e86e24124b2L, EBUInt16);
    builder.put(0x726a4e86e24124b1L, EBUInt32);
    builder.put(0x726a4e86e24124b3L, EBUInt64);
    builder.put(0x726a4e86e24124b4L, EBUInt8);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
