#pragma once
//this file is generated by exchbuf(https://github.com/ChrisYan6807/exchbuf), please do NOT edit it manually!!!
#include "eb_common.hpp"

namespace sandbox3 {
using namespace EB::common;
using EB::common::operator<<;

using u8 = LittleEndian<uint8_t, std::numeric_limits<uint8_t>::min(), std::numeric_limits<uint8_t>::max(), 0_u8, 0, true>;

#pragma pack(1)
struct E1 {
    u8 ff1;
    u8 ff2;
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<const char*>(this);}
    char* end() {return begin()+size();}
    const char* cend() const {return cbegin()+size();}
    static constexpr size_t fixed_size() noexcept {return sizeof(E1);}
    size_t size() {return fixed_size();}
    size_t size() const {return fixed_size();}
    static size_t wire_size(const char* p) {return reinterpret_cast<const E1*>(p)->size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const E1& msg) {
    os << "E1{";
    os << "ff1=" << msg.ff1 << ";"
       << "ff2=" << msg.ff2 << ";"
       << "}";
    return os;
}

#pragma pack(1)
struct M1 {
    u8 f1;
    u8 f2;
    BlockRef<E1> m1() {return BlockRef<E1>(begin()+fixed_size(), f1);}
    BlockRef<E1> m1() const {return BlockRef<E1>(cbegin()+fixed_size(), f1);}
    FloatingRef<u8> f3() {return FloatingRef<u8>(m1().end());}
    FloatingRef<u8> f3() const {return FloatingRef<u8>(m1().cend());}
    BlockRef<E1> m2() {return BlockRef<E1>(f3().end(), f1);}
    BlockRef<E1> m2() const {return BlockRef<E1>(f3().cend(), f1);}
    char* begin() {return reinterpret_cast<char*>(this);}
    const char* cbegin() const {return reinterpret_cast<const char*>(this);}
    char* end() {return begin()+size();}
    const char* cend() const {return cbegin()+size();}
    static constexpr size_t fixed_size() noexcept {return sizeof(M1);}
    size_t size() {return m2().end()-begin();}
    size_t size() const {return m2().cend()-cbegin();}
    static size_t wire_size(const char* p) {return reinterpret_cast<const M1*>(p)->size();}
};
#pragma pack()
inline std::ostream& operator<<(std::ostream& os, const M1& msg) {
    os << "M1{";
    os << "f1=" << msg.f1 << ";"
       << "f2=" << msg.f2 << ";"
       << "m1=" << const_cast<M1&>(msg).m1() << ";"
       << "f3=" << const_cast<M1&>(msg).f3() << ";"
       << "m2=" << const_cast<M1&>(msg).m2() << ";"
       << "}";
    return os;
}
} // end of namespace sandbox3


